// ─── RIBBON LIBRARY ─────────────────────────────────────────────────────────
// Sources:
//   - EZRackBuilder / USAMM — 1118 real US awards, all branches + auxiliaries
//   - medals.org.uk — 1274 international awards across 31 countries + UN
// Total: 215 ribbons. Auto-generated. DO NOT hand-edit.

export interface RibbonTemplate {
  country: string;
  branch: string;
  name: string;
  url: string;
  sku?: string;
}

export const RIBBON_COUNTRIES: string[] = ['United States', 'NATO', 'United Nations', 'United Kingdom', 'Australia', 'Canada', 'New Zealand', 'Belgium', 'France', 'Italy', 'Greece', 'Norway', 'Netherlands', 'Russia', 'Germany (NVA)', 'Poland', 'Luxembourg'];

export const RIBBON_BRANCHES_BY_COUNTRY: Record<string, string[]> = {
  'United States': ['US Gallantry', 'US Orders & Distinguished Service', 'US Commendations', 'US Campaign Medals', 'US Service Medals', 'US Long Service', 'US Commemorative'],
  'United Nations': ['United Nations'],
  'NATO': ['NATO'],
  'United Kingdom': ['UK Gallantry', 'UK Orders', 'UK Commendations', 'UK Campaign Medals', 'UK Service Medals', 'UK Jubilee Medals'],
  'Australia': ['Australia Gallantry', 'Australia Orders', 'Australia Commendations', 'Australia Campaign Medals', 'Australia Service Medals', 'Australia Jubilee & Commemorative'],
  'Canada': ['Canada Gallantry', 'Canada Orders', 'Canada Campaign Medals', 'Canada Service Medals', 'Canada Jubilee & Commemorative'],
  'New Zealand': ['New Zealand Gallantry', 'New Zealand Orders', 'New Zealand Campaign Medals', 'New Zealand Service Medals', 'New Zealand Jubilee & Commemorative'],
  'Belgium': ['Belgium Orders', 'Belgium Gallantry & Crosses', 'Belgium Campaign Medals'],
  'France': ['France Orders', 'France Gallantry & Crosses', 'France Campaign Medals'],
  'Italy': ['Italy Orders', 'Italy Gallantry & Crosses', 'Italy Campaign Medals'],
  'Greece': ['Greece Orders', 'Greece Gallantry & Crosses', 'Greece Campaign Medals'],
  'Norway': ['Norway Orders', 'Norway Gallantry & Crosses', 'Norway Campaign Medals'],
  'Netherlands': ['Netherlands Orders', 'Netherlands Gallantry & Crosses', 'Netherlands Campaign Medals'],
  'Russia': ['Russia Gallantry', 'Russia Orders & Distinguished Service', 'Russia Commendations'],
  'Germany (NVA)': ['Germany (NVA) Orders & Distinguished Service', 'Germany (NVA) Long Service', 'Germany (NVA) Commemorative'],
  'Poland': ['Poland Orders', 'Poland Gallantry & Crosses'],
  'Luxembourg': ['Luxembourg Orders', 'Luxembourg Gallantry & Crosses'],
};

export const RIBBON_TEMPLATES: RibbonTemplate[] = [  // ─── INTERNATIONAL ───
  // ─── NATO ───
  // ─── UNITED NATIONS ───



  // === UNITED NATIONS ===
  { country: 'United Nations', branch: 'United Nations', name: 'UNTSO Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations032.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMOGIP Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations034.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNFICYP Medal (Cyprus)', url: 'https://www.medals.pl/int/r/unfic.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNDOF Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations047.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNIFIL Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations018.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNIIMOG Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations052.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTAG Medal (Namibia)', url: 'https://www.medals.pl/int/r/untag.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'ONUCA Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations057.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNIKOM Medal (Iraq/Kuwait)', url: 'https://www.medals.pl/int/r/unikom.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAVEM Medal (Angola)', url: 'https://www.medals.pl/int/r/unavem.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MINURSO Medal (Western Sahara)', url: 'https://www.medals.pl/int/r/minurso.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'ONUSAL Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations062.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNPROFOR Medal (Bosnia)', url: 'https://www.medals.pl/int/r/unprofor.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAMIC Medal (Cambodia)', url: 'https://www.medals.pl/int/r/unamic.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTAC Medal (Cambodia)', url: 'https://www.medals.pl/int/r/untac.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOSOM Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations070.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'ONUMOZ Medal (Mozambique)', url: 'https://www.medals.pl/int/r/onumoz.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAMIR Medal (Rwanda)', url: 'https://www.medals.pl/int/r/unamir.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIH Medal (Haiti)', url: 'https://www.medals.pl/int/r/unmih.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMIG Medal (Georgia)', url: 'https://www.medals.pl/int/r/unomig.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMIL Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations078.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMUR Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations079.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMOT Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations024.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIBH Medal (Bosnia)', url: 'https://www.medals.pl/int/r/unmibh.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMOP Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations083.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTAES Medal (E. Slavonia)', url: 'https://www.medals.pl/int/r/untaes.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MINUGUA Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations006.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MINURCA Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations087.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNPSG Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations089.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMSIL Medal (Sierra Leone)', url: 'https://www.medals.pl/int/r/unomsil.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIK Medal (Kosovo)', url: 'https://www.medals.pl/int/r/unmik.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAMET Medal (East Timor)', url: 'https://www.medals.pl/int/r/unamet.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNPREDEP Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations097.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MONUC Medal (Congo)', url: 'https://www.medals.pl/int/r/monuc.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMEE Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations104.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNSSM Medal (Special Service)', url: 'https://www.medals.pl/int/r/unssm.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNHQ Medal (HQ Service)', url: 'https://www.medals.pl/int/r/unhq.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIL Medal (Liberia)', url: 'https://www.medals.pl/int/r/unmil.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIS Medal (Sudan)', url: 'https://www.medals.pl/int/r/unmis.gif' },
  { country: 'International', branch: 'United Nations', name: 'United Nations Medal', url: 'https://www.uniformribbons.com/image/un_medal_ribbon.png' },
  { country: 'International', branch: 'United Nations', name: 'United Nations Special Service Medal', url: 'https://www.uniformribbons.com/image/un_special_service_medal_ribbon.png' },


  // === NATO ===
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal Meritorious', url: 'https://www.uniformribbons.com/image/nato_medal_meritorious_ribbon.png' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Bosnia)', url: 'https://www.uniformribbons.com/image/nato_bosnia_ribbon.png' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Kosovo)', url: 'https://www.uniformribbons.com/image/nato_kosovo_ribbon.png' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Non-Article 5)', url: 'https://www.uniformribbons.com/image/nato_medal_non_article_5_ribbon.png' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (ISAF - Afghanistan)', url: 'https://www.uniformribbons.com/image/nato_isaf_ribbon.png' },
  { country: 'International', branch: 'NATO', name: 'Multinational Force and Observers Medal', url: 'https://www.uniformribbons.com/image/mfo_medal_ribbon.png' },
  { country: 'International', branch: 'NATO', name: 'Inter-American Defense Board Medal', url: 'https://www.uniformribbons.com/image/iadb_medal_ribbon.png' },

  // ── United Kingdom ──────────────────────────────────────────────
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Victoria Cross (VC)', url: 'https://www.medals.pl/bc/r/uk1vc.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Conspicuous Gallantry Cross (CGC)', url: 'https://www.medals.pl/bc/r/uk1cgc.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'King\'s/Queen\'s Commendation for Bravery (KCB/QCB)', url: 'https://www.medals.pl/bc/r/uk1bqcb.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'King\'s/Queen\'s Commendation for Bravery in the Air', url: 'https://www.medals.pl/bc/r/uk1bqcba.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'King\'s/Queen\'s Commendation for Valuable Service', url: 'https://www.medals.pl/bc/r/uk1bqcvs.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'Mention in Despatches (MID)', url: 'https://www.medals.pl/bc/r/uk1bmid2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'South Atlantic Medal 1982 (Falklands)', url: 'https://www.medals.pl/bc/r/uk1msa1.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Gulf Medal 1991', url: 'https://www.medals.pl/bc/r/uk1mgu.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Operational Service Medal - Sierra Leone', url: 'https://www.medals.pl/bc/r/uk1mos_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Operational Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/uk1mosaf_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Iraq Campaign Medal 2003 (Op Telic)', url: 'https://www.medals.pl/bc/r/uk1miqc_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Operational Service Medal - Congo', url: 'https://www.medals.pl/bc/r/uk1mosco_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Iraq Reconstruction Service Medal', url: 'https://www.medals.pl/bc/r/uk1mirs.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Civilian Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/uk1mcsaf.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Accumulated Campaign Service Medal (1994-2011)', url: 'https://www.medals.pl/bc/r/uk1mas.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Accumulated Campaign Service Medal (2011)', url: 'https://www.medals.pl/bc/r/uk1macb.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'King\'s/Queen\'s Volunteer Reserves Medal (KVRM/QVRM)', url: 'https://www.medals.pl/bc/r/uk1mqvr.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Volunteer Reserves Service Medal (VRSM)', url: 'https://www.medals.pl/bc/r/uk1mvrs.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Volunteer Reserves Service Medal - HAC', url: 'https://www.medals.pl/bc/r/uk1mhac.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Northern Ireland Home Service Medal', url: 'https://www.medals.pl/bc/r/uk1mhsni.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Royal Fleet Auxiliary Service Medal', url: 'https://www.medals.pl/bc/r/uk1mrfa.gif' },
  { country: 'United Kingdom', branch: 'UK Jubilee Medals', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'United Kingdom', branch: 'UK Jubilee Medals', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },

  // ── Australia ────────────────────────────────────────────────────
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Star of Gallantry (SG)', url: 'https://www.medals.pl/bc/r/au2sga.gif' },
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Medal for Gallantry (MG)', url: 'https://www.medals.pl/bc/r/au2mga.gif' },
  { country: 'Australia', branch: 'Australia Commendations', name: 'Commendation for Gallantry', url: 'https://www.medals.pl/bc/r/au2coga.gif' },
  { country: 'Australia', branch: 'Australia Commendations', name: 'Commendation for Distinguished Service', url: 'https://www.medals.pl/bc/r/au2cods.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Distinguished Service Cross (DSC)', url: 'https://www.medals.pl/bc/r/au2cds.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Conspicuous Service Cross (CSC)', url: 'https://www.medals.pl/bc/r/au2ccs.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Distinguished Service Medal (DSM)', url: 'https://www.medals.pl/bc/r/au2mds.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Conspicuous Service Medal (CSM)', url: 'https://www.medals.pl/bc/r/au2mcs.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Defence Force Long Service Medal', url: 'https://www.medals.pl/bc/r/au2mlsd.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Reserve Force Decoration (RFD)', url: 'https://www.medals.pl/bc/r/au2drf.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Reserve Force Medal', url: 'https://www.medals.pl/bc/r/au2mrf.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Defence Medal', url: 'https://www.medals.pl/bc/r/au2mad.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'Afghanistan Medal', url: 'https://www.medals.pl/bc/r/au2maf.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'Iraq Medal', url: 'https://www.medals.pl/bc/r/au2miq.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Australian Centenary Medal 2000', url: 'https://www.medals.pl/bc/r/au2mce.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Unit Citation for Gallantry', url: 'https://www.medals.pl/bc/r/au2ucga1.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Meritorious Unit Citation', url: 'https://www.medals.pl/bc/r/au2ucms1.gif' },

  // ── Canada ───────────────────────────────────────────────────────
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Star of Military Valour (SMV)', url: 'https://www.medals.pl/bc/r/ca2smv.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Medal of Military Valour (MMV)', url: 'https://www.medals.pl/bc/r/ca2mmv.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Meritorious Service Cross - Military (MSC)', url: 'https://www.medals.pl/bc/r/ca2cmsm.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Meritorious Service Medal - Military (MSM)', url: 'https://www.medals.pl/bc/r/ca2mmsm.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Gulf and Kuwait Medal', url: 'https://www.medals.pl/bc/r/ca2mgk1.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Somalia Medal', url: 'https://www.medals.pl/bc/r/ca2mso.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'South West Asia Service Medal (SWASM)', url: 'https://www.medals.pl/bc/r/ca2mswass.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Campaign Star - Afghanistan', url: 'https://www.medals.pl/bc/r/ca2sgcaf.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Campaign Star - SW Asia', url: 'https://www.medals.pl/bc/r/ca2sgcswa.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - Expedition', url: 'https://www.medals.pl/bc/r/ca2mosexp.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - SW Asia', url: 'https://www.medals.pl/bc/r/ca2mosswa.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Special Service Medal (SSM)', url: 'https://www.medals.pl/bc/r/ca2mss.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Canadian Peacekeeping Service Medal (CPSM)', url: 'https://www.medals.pl/bc/r/ca2mpe.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'Canada', branch: 'Canada Jubilee & Commemorative', name: '125th Anniversary of Confederation Medal 1992', url: 'https://www.medals.pl/bc/r/ca2m125.gif' },
  { country: 'Canada', branch: 'Canada Jubilee & Commemorative', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'Canada', branch: 'Canada Jubilee & Commemorative', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },

  // ── New Zealand ──────────────────────────────────────────────────
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'New Zealand Cross (NZC)', url: 'https://www.medals.pl/bc/r/nz2nzc.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Gallantry Star (NZGS)', url: 'https://www.medals.pl/bc/r/nz2nzgs.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Bravery Star (NZBS)', url: 'https://www.medals.pl/bc/r/nz2nzbs.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Gallantry Decoration (NZGD)', url: 'https://www.medals.pl/bc/r/nz2nzgd.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Bravery Decoration (NZBD)', url: 'https://www.medals.pl/bc/r/nz2nzbd.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Gallantry Medal (NZGM)', url: 'https://www.medals.pl/bc/r/nz2nzgm.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Bravery Medal (NZBM)', url: 'https://www.medals.pl/bc/r/nz2nzbm.gif' },
  { country: 'New Zealand', branch: 'New Zealand Orders', name: 'Order of New Zealand (ONZ)', url: 'https://www.medals.pl/bc/r/nz2onz.gif' },
  { country: 'New Zealand', branch: 'New Zealand Orders', name: 'New Zealand Order of Merit', url: 'https://www.medals.pl/bc/r/nz2nzom.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'Distinguished Service Decoration (DSD)', url: 'https://www.medals.pl/bc/r/nz2dsd.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Meritorious Service Medal', url: 'https://www.medals.pl/bc/r/nz2mms.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Armed Forces Award', url: 'https://www.medals.pl/bc/r/nz2aarf.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'Operational Service Medal (NZ)', url: 'https://www.medals.pl/bc/r/nz2mos.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/nz2mgsaf.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'GSM - Afghanistan (secondary area)', url: 'https://www.medals.pl/bc/r/nz2mgsafb.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Iraq 2003', url: 'https://www.medals.pl/bc/r/nz2mgsiq.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'NZ East Timor Medal', url: 'https://www.medals.pl/bc/r/nz2met.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Solomon Islands', url: 'https://www.medals.pl/bc/r/nz2mgssi.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Timor Leste', url: 'https://www.medals.pl/bc/r/nz2mgstl.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'NZ General Service Medal (Warlike)', url: 'https://www.medals.pl/bc/r/nz2mgsw.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'NZ General Service Medal (Non-Warlike)', url: 'https://www.medals.pl/bc/r/nz2mgsp.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Army LS & GC Medal', url: 'https://www.medals.pl/bc/r/uk1mlsa.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Navy LS & GC Medal', url: 'https://www.medals.pl/bc/r/uk1mlsn.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Air Force LS & GC Medal', url: 'https://www.medals.pl/bc/r/uk1mlsaf.gif' },
  { country: 'New Zealand', branch: 'New Zealand Jubilee & Commemorative', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'New Zealand', branch: 'New Zealand Jubilee & Commemorative', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'Special Service Medal - Asian Tsunami', url: 'https://www.medals.pl/bc/r/nz2mssat.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'George Cross (GC)', url: 'https://www.medals.pl/bc/r/uk1gc.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Distinguished Service Order (DSO)', url: 'https://www.medals.pl/bc/r/uk1ods.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Military Cross (MC)', url: 'https://www.medals.pl/bc/r/uk1cmm.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Distinguished Service Cross (DSC)', url: 'https://www.medals.pl/bc/r/uk1cds.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Distinguished Flying Cross (DFC)', url: 'https://www.medals.pl/bc/r/uk1cdfb.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Air Force Cross (AFC)', url: 'https://www.medals.pl/bc/r/uk1cafb.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'George Medal (GM)', url: 'https://www.medals.pl/bc/r/uk1mge.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Queen/King Gallantry Medal (QGM/KGM)', url: 'https://www.medals.pl/bc/r/uk1mqg.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Royal Red Cross (RRC)', url: 'https://www.medals.pl/bc/r/uk1crrc.gif' },
  { country: 'United Kingdom', branch: 'UK Orders', name: 'Order of the British Empire - Military (OBE)', url: 'https://www.medals.pl/bc/r/uk1obemb.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'British Empire Medal - Military (BEM)', url: 'https://www.medals.pl/bc/r/uk1mbemb.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Meritorious Service Medal (MSM)', url: 'https://www.medals.pl/bc/r/uk1mmsa.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Campaign Service Medal 1962-2007', url: 'https://www.medals.pl/bc/r/uk1mcs_m.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Polar Medal', url: 'https://www.medals.pl/bc/r/uk1mpo.gif' },
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Star of Courage (SC)', url: 'https://www.medals.pl/bc/r/au2sco1.gif' },
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Bravery Medal (BM)', url: 'https://www.medals.pl/bc/r/au2mbr1.gif' },
  { country: 'Australia', branch: 'Australia Commendations', name: 'Commendation for Brave Conduct', url: 'https://www.medals.pl/bc/r/au2cobc.gif' },
  { country: 'Australia', branch: 'Australia Orders', name: 'Medal of the Order of Australia - Military Division (OAM)', url: 'https://www.medals.pl/bc/r/au2moam.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Antarctic Medal (AAM)', url: 'https://www.medals.pl/bc/r/au2maa.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Defence Force Service Medal (DFSM)', url: 'https://www.medals.pl/bc/r/au2mdfs.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Service Medal (ASM)', url: 'https://www.medals.pl/bc/r/au2mas.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Cross of Valour (CV)', url: 'https://www.medals.pl/bc/r/ca2cva.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Star of Courage (SC)', url: 'https://www.medals.pl/bc/r/ca2sco.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Medal of Bravery (MB)', url: 'https://www.medals.pl/bc/r/ca2mbr.gif' },
  { country: 'Canada', branch: 'Canada Orders', name: 'Order of Military Merit (OMM)', url: 'https://www.medals.pl/bc/r/ca2omm1.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Sacrifice Medal', url: 'https://www.medals.pl/bc/r/ca2msa.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Canadian Forces Decoration (CD)', url: 'https://www.medals.pl/bc/r/ca2dcf.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Campaign Star - Expedition', url: 'https://www.medals.pl/bc/r/ca2sgcexp.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/ca2mgsaf.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Service Medal - South West Asia', url: 'https://www.medals.pl/bc/r/ca2mgsswa.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Service Medal - Expedition', url: 'https://www.medals.pl/bc/r/ca2mgsexp.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - South Sudan', url: 'https://www.medals.pl/bc/r/ca2moss.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - Expedition', url: 'https://www.medals.pl/bc/r/ca2mosexp.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'New Zealand Antarctic Medal (NZAM)', url: 'https://www.medals.pl/bc/r/nz2manz.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Army Long Service & Good Conduct Medal', url: 'https://www.medals.pl/bc/r/uk1mlsa.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Naval Long Service & Good Conduct Medal', url: 'https://www.medals.pl/bc/r/uk1mlsn.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'RAF Long Service & Good Conduct Medal', url: 'https://www.medals.pl/bc/r/uk1mlsaf.gif' },
  // ─── BELGIUM ────────────────────────────────────────────────────────────────
  { country: 'Belgium', branch: 'Belgium Orders', name: "Order of Léopold", url: 'https://www.medals.pl/be/r/be1ole4.gif' },
  { country: 'Belgium', branch: 'Belgium Orders', name: "Order of Léopold II", url: 'https://www.medals.pl/be/r/be1oleii.gif' },

  // ─── FRANCE ─────────────────────────────────────────────────────────────────
  // Gallantry
  { country: 'France', branch: 'France Gallantry', name: 'Legion d'Honneur', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Legion_Honneur_Chevalier_ribbon.svg/250px-Legion_Honneur_Chevalier_ribbon.svg.png' },
  { country: 'France', branch: 'France Gallantry', name: 'Medaille Militaire', url: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Ruban_de_la_M%C3%A9daille_militaire.PNG' },
  { country: 'France', branch: 'France Gallantry', name: 'Croix de Guerre - Theatres d'Operations Exterieures', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Croix_de_Guerre_des_Theatres_d%27Operations_Exterieurs_ribbon.svg/250px-Croix_de_Guerre_des_Theatres_d%27Operations_Exterieurs_ribbon.svg.png' },
  { country: 'France', branch: 'France Gallantry', name: 'Croix de la Valeur Militaire', url: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Ruban_de_la_Croix_de_la_Valeur_militaire.PNG' },
  { country: 'France', branch: 'France Gallantry', name: 'Croix du Combattant', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Croix_du_Combattant_%281930_France%29_ribbon.svg/250px-Croix_du_Combattant_%281930_France%29_ribbon.svg.png' },
  { country: 'France', branch: 'France Gallantry', name: 'Croix du Combattant Volontaire (1983)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Croix_du_Combattant_Volontaire_1939-1945_ribbon.svg/250px-Croix_du_Combattant_Volontaire_1939-1945_ribbon.svg.png' },
  // Orders & Distinguished Service
  { country: 'France', branch: 'France Orders & Distinguished Service', name: 'Ordre National du Merite', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Ordre_national_du_Merite_Chevalier_ribbon.svg/250px-Ordre_national_du_Merite_Chevalier_ribbon.svg.png' },
  // Service Medals
  { country: 'France', branch: 'France Service Medals', name: 'Medaille de la Defense Nationale', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Medaille_de_la_Defense_Nationale_Bronze_ribbon.svg/250px-Medaille_de_la_Defense_Nationale_Bronze_ribbon.svg.png' },
  { country: 'France', branch: 'France Service Medals', name: 'Medaille d'Outre-Mer', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Medaille_d%27Outre-Mer_%28Coloniale%29_ribbon.svg/250px-Medaille_d%27Outre-Mer_%28Coloniale%29_ribbon.svg.png' },
  { country: 'France', branch: 'France Service Medals', name: 'Medaille des Services Militaires Volontaires', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Medaille_des_Services_Militaires_Volontaires_Bronze_ribbon.svg/250px-Medaille_des_Services_Militaires_Volontaires_Bronze_ribbon.svg.png' },
  { country: 'France', branch: 'France Service Medals', name: 'Medaille des Blesses de Guerre', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Medaille_%28Insigne%29_des_Blesses_Militaires_ribbon.svg/250px-Medaille_%28Insigne%29_des_Blesses_Militaires_ribbon.svg.png' },
  { country: 'France', branch: 'France Service Medals', name: 'Medaille d'honneur du Service de Sante des Armees', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Medaille_d%27honneur_du_Service_de_Sante_des_Armees_Bronze_ribbon.svg/250px-Medaille_d%27honneur_du_Service_de_Sante_des_Armees_Bronze_ribbon.svg.png' },
  // Campaign Medals
  { country: 'France', branch: 'France Campaign Medals', name: 'Medaille Commemorative Francaise (Operations Exterieures)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Medaille_commemorative_Francaise_ribbon.svg/250px-Medaille_commemorative_Francaise_ribbon.svg.png' },
  { country: 'France', branch: 'France Campaign Medals', name: 'Medaille de la Protection Militaire du Territoire', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Medaille_de_la_protection_militaire_du_territoire.svg/250px-Medaille_de_la_protection_militaire_du_territoire.svg.png' },

  // ─── ITALY ──────────────────────────────────────────────────────────────────
  { country: 'Italy', branch: 'Italy Orders', name: "Order of St. Maurice & St. Lazarus", url: 'https://www.medals.pl/it/r/it1oml.gif' },
  { country: 'Italy', branch: 'Italy Orders', name: 'Order of Merit of the Italian Republic', url: 'https://www.medals.pl/it/r/it2ome.gif' },
  { country: 'Italy', branch: 'Italy Gallantry & Crosses', name: 'Medal for Military Valor', url: 'https://www.medals.pl/it/r/it2mvmi2.gif' },
  { country: 'Italy', branch: 'Italy Gallantry & Crosses', name: 'War Merit Cross', url: 'https://www.medals.pl/it/r/it2cmg.gif' },

  // ─── GREECE ─────────────────────────────────────────────────────────────────
  { country: 'Greece', branch: 'Greece Orders', name: 'Order of the Redeemer', url: 'https://www.medals.pl/gr/r/gr1ore.gif' },
  { country: 'Greece', branch: 'Greece Orders', name: 'Order of the Phoenix', url: 'https://www.medals.pl/gr/r/gr1oph.gif' },
  { country: 'Greece', branch: 'Greece Gallantry & Crosses', name: 'Cross of Valour', url: 'https://www.medals.pl/gr/r/gr1cva.gif' },
  { country: 'Greece', branch: 'Greece Gallantry & Crosses', name: 'Medal for Outstanding Acts', url: 'https://www.medals.pl/gr/r/gr1moab.gif' },

  // ─── NORWAY ─────────────────────────────────────────────────────────────────
  { country: 'Norway', branch: 'Norway Orders', name: 'Order of St. Olaf', url: 'https://www.medals.pl/no/r/no1ool.gif' },
  { country: 'Norway', branch: 'Norway Gallantry & Crosses', name: 'War Cross', url: 'https://www.medals.pl/no/r/no1cw.gif' },
  { country: 'Norway', branch: 'Norway Orders', name: "St. Olaf's Medal with Oak Wreath", url: 'https://www.medals.pl/no/r/no1molo.gif' },

  // ─── NETHERLANDS ────────────────────────────────────────────────────────────
  { country: 'Netherlands', branch: 'Netherlands Orders', name: 'Military Order of William', url: 'https://www.medals.pl/nl/r/nl1owi.gif' },
  { country: 'Netherlands', branch: 'Netherlands Orders', name: 'Order of Orange-Nassau', url: 'https://www.medals.pl/nl/r/nl1oon.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Bronze Lion', url: 'https://www.medals.pl/nl/r/nl1bli.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Bronze Cross', url: 'https://www.medals.pl/nl/r/nl1cbr.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Flying Cross', url: 'https://www.medals.pl/nl/r/nl1cfl.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Cross of Merit', url: 'https://www.medals.pl/nl/r/nl1cme.gif' },

  // ─── RUSSIA ─────────────────────────────────────────────────────────────────
  // Gallantry
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Order of Saint George - 1st Class', url: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/RUS_Order_of_Saint_George_1st_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Order of Saint George - 2nd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/4/47/RUS_Order_of_Saint_George_2nd_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Order of Saint George - 3rd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/RUS_Order_of_Saint_George_3rd_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Order of Saint George - 4th Class', url: 'https://upload.wikimedia.org/wikipedia/commons/1/18/RUS_Order_of_Saint_George_4th_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Cross of Saint George - 1st Class', url: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/RUS_Cross_of_Saint_George_1st_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Cross of Saint George - 2nd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/7/78/RUS_Cross_of_Saint_George_2nd_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Cross of Saint George - 3rd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/RUS_Cross_of_Saint_George_3rd_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Cross of Saint George - 4th Class', url: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/RUS_Cross_of_Saint_George_4th_class_ribbon_2000.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Order of Courage', url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RUS_Order_of_Courage_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Medal for Courage', url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RUS_Medal_For_Courage_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Medal for Bravery - 1st Class', url: 'https://upload.wikimedia.org/wikipedia/commons/5/56/RUS_Medal_for_Bravery_1-st_BAR_2023.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Medal for Bravery - 2nd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/RUS_Medal_for_Bravery_2-st_BAR_2023.svg' },
  { country: 'Russia', branch: 'Russia Gallantry', name: 'Order of Saint Andrew the Apostle (with Swords)', url: 'https://upload.wikimedia.org/wikipedia/commons/9/97/RUS_Saint_Andrew_the_Apostle_the_First-Called_Order_with_swords_ribbon.svg' },
  // Orders & Distinguished Service
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Alexander Nevsky', url: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Order_of_Alexander_Nevsky_2010_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Suvorov', url: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/RUS_Order_of_Suvorov_ribbon_2010.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Kutuzov', url: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/RUS_Order_of_Kutuzov_ribbon_2010.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Ushakov', url: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/RUS_Order_of_Ushakov_ribbon_2010.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Nakhimov', url: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/RUS_Order_of_Nakhimov_ribbon_2010.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Zhukov', url: 'https://upload.wikimedia.org/wikipedia/commons/8/80/RUS_Order_of_Zhukov_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Military Merit', url: 'https://upload.wikimedia.org/wikipedia/commons/9/93/RUS_Order_of_Military_Merit_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order of Naval Merit', url: 'https://upload.wikimedia.org/wikipedia/commons/c/c0/RUS_Order_of_Naval_Merit_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order For Merit to the Fatherland - 3rd Class (with Swords)', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/RUS_For_Merit_to_the_Fatherland_Order_3rd_class_with_swords_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Orders & Distinguished Service', name: 'Order For Merit to the Fatherland - 4th Class (with Swords)', url: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/RUS_For_Merit_to_the_Fatherland_Order_4th_class_with_swords_ribbon.svg' },
  // Commendations
  { country: 'Russia', branch: 'Russia Commendations', name: 'Medal of Suvorov', url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/RUS_Medal_of_Suvorov_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Commendations', name: 'Medal of Ushakov', url: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/RUS_Medal_of_Ushakov_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Commendations', name: 'Medal of Zhukov', url: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/RUS_Medal_of_Zhukov_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Commendations', name: 'Medal of Nesterov', url: 'https://upload.wikimedia.org/wikipedia/commons/2/23/RUS_Medal_of_Nesterov_ribbon.svg' },
  { country: 'Russia', branch: 'Russia Commendations', name: 'Medal for Distinction in Protection of State Borders', url: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/RUS_Medal_For_Distinction_in_the_Protection_of_the_State_Borders_ribbon.svg' },


  // ─── AUSTRIA ──────────────────────────────────────────────────────────────
  // Gallantry
  { country: 'Austria', branch: 'Austria Gallantry', name: 'Wound Medal - 1st Wound', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/AUT_Verwundetenmedaille_BAR.svg/250px-AUT_Verwundetenmedaille_BAR.svg.png' },
  { country: 'Austria', branch: 'Austria Gallantry', name: 'Wound Medal - 2nd Wound', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/AUT_Verwundetenmedaille_2x_BAR.svg/250px-AUT_Verwundetenmedaille_2x_BAR.svg.png' },
  // Commendations
  { country: 'Austria', branch: 'Austria Commendations', name: 'Military Recognition Medal', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/AUT_Milit%C3%A4r-Anerkennungsmedaille_BAR.svg/250px-AUT_Milit%C3%A4r-Anerkennungsmedaille_BAR.svg.png' },
  // Campaign Medals
  { country: 'Austria', branch: 'Austria Campaign Medals', name: 'Armed Forces Operations Medal - Foreign Operations', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/AUT_Einsatzmedaille_a_BAR.svg/250px-AUT_Einsatzmedaille_a_BAR.svg.png' },
  // Service Medals
  { country: 'Austria', branch: 'Austria Service Medals', name: 'Armed Forces Operations Medal - Military Defence', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/AUT_Einsatzmedaille_d_BAR.svg/250px-AUT_Einsatzmedaille_d_BAR.svg.png' },
  // Long Service
  { country: 'Austria', branch: 'Austria Long Service', name: 'Military Service Award - 1st Class', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/AUT_Wehrdienstzeichen_1._Klasse_BAR.svg/250px-AUT_Wehrdienstzeichen_1._Klasse_BAR.svg.png' },
  { country: 'Austria', branch: 'Austria Long Service', name: 'Military Service Award - 2nd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/AUT_Wehrdienstzeichen_2._Klasse_BAR.svg/250px-AUT_Wehrdienstzeichen_2._Klasse_BAR.svg.png' },
  { country: 'Austria', branch: 'Austria Long Service', name: 'Military Service Award - 3rd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/AUT_Wehrdienstzeichen_3._Klasse_BAR.svg/250px-AUT_Wehrdienstzeichen_3._Klasse_BAR.svg.png' },
  { country: 'Austria', branch: 'Austria Long Service', name: 'Militia Medal', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/AUT_Milizmedaille_BAR.svg/250px-AUT_Milizmedaille_BAR.svg.png' },


  // ─── ESTONIA ──────────────────────────────────────────────────────────────
  // Gallantry
  { country: 'Estonia', branch: 'Estonia Gallantry', name: 'Cross of Liberty - 1st Division', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/EST_Cross_of_Liberty_I_division_ribbon.svg/250px-EST_Cross_of_Liberty_I_division_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Gallantry', name: 'Cross of Liberty - 2nd Division', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/EST_Cross_of_Liberty_II_division_ribbon.svg/250px-EST_Cross_of_Liberty_II_division_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Gallantry', name: 'Cross of Liberty - 3rd Division', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/EST_Cross_of_Liberty_III_division_ribbon.svg/250px-EST_Cross_of_Liberty_III_division_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Gallantry', name: 'Defence Forces Decoration for Battle Merit', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/EST_Defence_Forces_Decoration_for_battle_merit_ribbon.svg/250px-EST_Defence_Forces_Decoration_for_battle_merit_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Gallantry', name: 'Navy Cross', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/EST_Navy_Cross_ribbon.svg/250px-EST_Navy_Cross_ribbon.svg.png' },
  // Commendations
  { country: 'Estonia', branch: 'Estonia Commendations', name: 'Defence Forces Decoration for Defence Merit', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/EST_Defence_Forces_Decoration_for_defence_merit_ribbon.svg/250px-EST_Defence_Forces_Decoration_for_defence_merit_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Commendations', name: 'Defence Forces Merit Cross for Meritorious Service', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/EST_Defence_Forces_Merit_Cross_for_meritorious_service_ribbon.svg/250px-EST_Defence_Forces_Merit_Cross_for_meritorious_service_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Commendations', name: 'Defence Forces Merit Cross for National Defence Merit', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/EST_Defence_Forces_Merit_Cross_for_national_defence_merit_ribbon.svg/250px-EST_Defence_Forces_Merit_Cross_for_national_defence_merit_ribbon.svg.png' },
  // Long Service
  { country: 'Estonia', branch: 'Estonia Long Service', name: 'Long Service Medal', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/EST_Kaitsev%C3%A4e_pikaajalise_teenistuse_medal.png/250px-EST_Kaitsev%C3%A4e_pikaajalise_teenistuse_medal.png' },
  { country: 'Estonia', branch: 'Estonia Long Service', name: 'White Cross of the Estonian Defence League - 1st Class', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/EST_White_Cross_of_the_Estonian_Defence_League_1st_class_ribbon.svg/250px-EST_White_Cross_of_the_Estonian_Defence_League_1st_class_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Long Service', name: 'White Cross of the Estonian Defence League - 2nd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/EST_White_Cross_of_the_Estonian_Defence_League_2nd_class_ribbon.svg/250px-EST_White_Cross_of_the_Estonian_Defence_League_2nd_class_ribbon.svg.png' },
  { country: 'Estonia', branch: 'Estonia Long Service', name: 'White Cross of the Estonian Defence League - 3rd Class', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/EST_White_Cross_of_the_Estonian_Defence_League_3rd_class_ribbon.svg/250px-EST_White_Cross_of_the_Estonian_Defence_League_3rd_class_ribbon.svg.png' },
  // Commemorative
  { country: 'Estonia', branch: 'Estonia Commemorative', name: 'Memorial Medal - 10 Years of the Re-Established Defence Forces', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/EST_Memorial_Medal_10_Years_of_the_Re-Established_Defence_Forces.png/250px-EST_Memorial_Medal_10_Years_of_the_Re-Established_Defence_Forces.png' },


  // ─── FINLAND ──────────────────────────────────────────────────────────────
  // Gallantry
  { country: 'Finland', branch: 'Finland Gallantry', name: 'Order of the Cross of Liberty - Grand Cross (Military)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/FIN_Order_of_the_Cross_of_Liberty_GCross_peace_military_BAR.svg/250px-FIN_Order_of_the_Cross_of_Liberty_GCross_peace_military_BAR.svg.png' },
  { country: 'Finland', branch: 'Finland Gallantry', name: 'Order of the Cross of Liberty - 1st Class with Star (Military)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/FIN_Order_of_the_Cross_of_Liberty_1Class_Star_peace_military_BAR.svg/250px-FIN_Order_of_the_Cross_of_Liberty_1Class_Star_peace_military_BAR.svg.png' },
  { country: 'Finland', branch: 'Finland Gallantry', name: 'Order of the Cross of Liberty - 1st Class (Military)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/FIN_Order_of_the_Cross_of_Liberty_1Class_peace_military_BAR.svg/250px-FIN_Order_of_the_Cross_of_Liberty_1Class_peace_military_BAR.svg.png' },
  { country: 'Finland', branch: 'Finland Gallantry', name: 'Order of the Cross of Liberty - 2nd Class (Military)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/FIN_Order_of_the_Cross_of_Liberty_2Class_peace_military_BAR.svg/250px-FIN_Order_of_the_Cross_of_Liberty_2Class_peace_military_BAR.svg.png' },
  { country: 'Finland', branch: 'Finland Gallantry', name: 'Order of the Cross of Liberty - 3rd Class (Military)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/FIN_Order_of_the_Cross_of_Liberty_3Class_peace_military_BAR.svg/250px-FIN_Order_of_the_Cross_of_Liberty_3Class_peace_military_BAR.svg.png' },
  { country: 'Finland', branch: 'Finland Gallantry', name: 'Order of the Cross of Liberty - 4th Class (Military)', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/FIN_Order_of_the_Cross_of_Liberty_4Class_peace_military_BAR.svg/250px-FIN_Order_of_the_Cross_of_Liberty_4Class_peace_military_BAR.svg.png' },
  // Commendations
  { country: 'Finland', branch: 'Finland Commendations', name: 'Medal for Military Merits', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/FIN_Military_Merit_Medal_BAR.svg/250px-FIN_Military_Merit_Medal_BAR.svg.png' },


  // ─── CROATIA ──────────────────────────────────────────────────────────────
  // Orders & Distinguished Service
  { country: 'Croatia', branch: 'Croatia Orders & Distinguished Service', name: 'Grand Order of King Tomislav', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Ribbon_of_an_order_of_king_Tomislav.png/250px-Ribbon_of_an_order_of_king_Tomislav.png' },
  { country: 'Croatia', branch: 'Croatia Orders & Distinguished Service', name: 'Order of Ban Jelacic', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Ribbon_of_an_Order_of_Ban_Jela%C4%8Di%C4%87.png/250px-Ribbon_of_an_Order_of_Ban_Jela%C4%8Di%C4%87.png' },
  { country: 'Croatia', branch: 'Croatia Orders & Distinguished Service', name: 'Order of the Croatian Cross', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Ribbon_of_an_Order_of_the_Croatian_Cross.png/250px-Ribbon_of_an_Order_of_the_Croatian_Cross.png' },
  // Gallantry
  { country: 'Croatia', branch: 'Croatia Gallantry', name: 'Order of Duke Trpimir', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Ribbon_of_the_Order_of_Duke_Trpimir.png/250px-Ribbon_of_the_Order_of_Duke_Trpimir.png' },
  { country: 'Croatia', branch: 'Croatia Gallantry', name: 'Order of Duke Domagoj', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Ribbon_of_an_Order_of_Duke_Domagoj.png/250px-Ribbon_of_an_Order_of_Duke_Domagoj.png' },
  { country: 'Croatia', branch: 'Croatia Gallantry', name: 'Order of Nikola Subic Zrinski', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ribbon_of_an_Order_of_Nikola_%C5%A0ubi%C4%87_Zrinski.png/250px-Ribbon_of_an_Order_of_Nikola_%C5%A0ubi%C4%87_Zrinski.png' },
  // Campaign Medals
  { country: 'Croatia', branch: 'Croatia Campaign Medals', name: 'Homeland's Gratitude Medal', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Homelands_Gratitude_Medal.jpg/250px-Homelands_Gratitude_Medal.jpg' },
  { country: 'Croatia', branch: 'Croatia Campaign Medals', name: 'Homeland Medal - Gold', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Zlatna_domovinska_medalja_-_mala_oznaka.jpg/250px-Zlatna_domovinska_medalja_-_mala_oznaka.jpg' },
  { country: 'Croatia', branch: 'Croatia Campaign Medals', name: 'Homeland Medal - Silver', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Srebrna_domovinska_medalja_-_mala_oznaka.jpg/250px-Srebrna_domovinska_medalja_-_mala_oznaka.jpg' },
  { country: 'Croatia', branch: 'Croatia Campaign Medals', name: 'Homeland Medal - Bronze', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Bron%C4%8Dana_domovinska_medalja_-_mala_oznaka.jpg/250px-Bron%C4%8Dana_domovinska_medalja_-_mala_oznaka.jpg' },
  // Service Medals
  { country: 'Croatia', branch: 'Croatia Service Medals', name: 'Medal of the Croatian Armed Forces - Gold', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Zlatna_medalja_Hrvatske_vojske_-_mala_oznaka.jpg/250px-Zlatna_medalja_Hrvatske_vojske_-_mala_oznaka.jpg' },
  { country: 'Croatia', branch: 'Croatia Service Medals', name: 'Medal of the Croatian Armed Forces - Silver', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Srebrna_medalja_Hrvatske_vojske.jpg/250px-Srebrna_medalja_Hrvatske_vojske.jpg' },
  { country: 'Croatia', branch: 'Croatia Service Medals', name: 'Medal of the Croatian Armed Forces - Bronze', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Bron%C4%8Dana_medalja_Hrvatske_vojske_-_mala_oznaka.jpg/250px-Bron%C4%8Dana_medalja_Hrvatske_vojske_-_mala_oznaka.jpg' },

  // ─── GERMANY (NVA) ──────────────────────────────────────────────────────────
  // Orders & Distinguished Service
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Orders & Distinguished Service', name: 'Militarischer Verdienstorden - Gold (Order of Military Merit - Gold)', url: 'https://www.medals.pl/de/r/drmvo1.gif' },
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Orders & Distinguished Service', name: 'Militarischer Verdienstorden - Silver (Order of Military Merit - Silver)', url: 'https://www.medals.pl/de/r/drmvo2.gif' },
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Orders & Distinguished Service', name: 'Militarischer Verdienstorden - Bronze (Order of Military Merit - Bronze)', url: 'https://www.medals.pl/de/r/drmvo3.gif' },
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Orders & Distinguished Service', name: 'Militarische Verdienstmedaille (Medal of Military Merit)', url: 'https://www.medals.pl/de/r/drmvm.gif' },
  // Long Service
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Long Service', name: 'Ehrenzeichen fur Verdienste in der Reservistenarbeit - Gold (Reserve Service Medal - Gold)', url: 'https://www.medals.pl/de/r/drmvres1.gif' },
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Long Service', name: 'Ehrenzeichen fur Verdienste in der Reservistenarbeit - Silver (Reserve Service Medal - Silver)', url: 'https://www.medals.pl/de/r/drmvres2.gif' },
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Long Service', name: 'Ehrenzeichen fur Verdienste in der Reservistenarbeit - Bronze (Reserve Service Medal - Bronze)', url: 'https://www.medals.pl/de/r/drmvres3.gif' },
  // Commemorative
  { country: 'Germany (NVA)', branch: 'Germany (NVA) Commemorative', name: 'Ehrenmedaille 30 Jahre Nationale Volksarmee (30th Anniversary of NVA Medal)', url: 'https://www.medals.pl/de/r/drmnva30.gif' },

  // ─── POLAND ─────────────────────────────────────────────────────────────────
  { country: 'Poland', branch: 'Poland Orders', name: 'Order Virtuti Militari', url: 'https://www.medals.pl/pl/r/pl4ovm.gif' },
  { country: 'Poland', branch: 'Poland Orders', name: 'Order of Polonia Restituta', url: 'https://www.medals.pl/pl/r/pl4opr.gif' },
  { country: 'Poland', branch: 'Poland Gallantry & Crosses', name: 'Cross of Valor', url: 'https://www.medals.pl/pl/r/pl2cvab.gif' },
  { country: 'Poland', branch: 'Poland Gallantry & Crosses', name: 'Cross of Merit', url: 'https://www.medals.pl/pl/r/pl2cme.gif' },

  // ─── LUXEMBOURG ─────────────────────────────────────────────────────────────
  { country: 'Luxembourg', branch: 'Luxembourg Orders', name: 'Order of Adolph of Nassau', url: 'https://www.medals.pl/lu/r/lu1oan.gif' },
  { country: 'Luxembourg', branch: 'Luxembourg Gallantry & Crosses', name: 'Croix de Guerre', url: 'https://www.medals.pl/lu/r/lu1cg.gif' },

  // United States
  { country: 'United States', branch: 'US Gallantry', name: 'Medal of Honor Ribbon', url: 'https://www.uniformribbons.com/image/medal_of_honor_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Army Distinguished Service Cross Ribbon', url: 'https://www.uniformribbons.com/image/army_distinguished_service_cross_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Defense Distinguished Service Ribbon', url: 'https://www.uniformribbons.com/image/defense_distinguished_service_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Army Distinguished Service Ribbon', url: 'https://www.uniformribbons.com/image/army_distinguished_service_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Silver Star Ribbon', url: 'https://www.uniformribbons.com/image/silver_star_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Defense Superior Service Ribbon', url: 'https://www.uniformribbons.com/image/defense_superior_service_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Legion of Merit Ribbon', url: 'https://www.uniformribbons.com/image/legion_of_merit_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Distinguished Flying Cross Ribbon', url: 'https://www.uniformribbons.com/image/distinguished_flying_cross_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Soldier\'s Medal Ribbon', url: 'https://www.uniformribbons.com/image/soldier_medal_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Bronze Star Ribbon', url: 'https://www.uniformribbons.com/image/bronze_star_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Purple Heart Ribbon', url: 'https://www.uniformribbons.com/image/purple_heart_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Defense Meritorious Service Ribbon', url: 'https://www.uniformribbons.com/image/defense_meritorious_service_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Meritorious Service Ribbon', url: 'https://www.uniformribbons.com/image/meritorious_service_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Air Medal Ribbon', url: 'https://www.uniformribbons.com/image/air_medal_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Joint Service Commendation Ribbon', url: 'https://www.uniformribbons.com/image/joint_service_commendation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Army Commendation Ribbon', url: 'https://www.uniformribbons.com/image/army_commendation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Joint Service Achievement Ribbon', url: 'https://www.uniformribbons.com/image/joint_service_achievement_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Army Achievement Ribbon', url: 'https://www.uniformribbons.com/image/army_achievement_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Army Presidential Unit Citation Ribbon', url: 'https://www.uniformribbons.com/image/army_presidential_unit_citation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Joint Service Meritorious Unit Ribbon', url: 'https://www.uniformribbons.com/image/joint_service_meritorious_unit_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Army Valorous Unit Award Ribbon', url: 'https://www.uniformribbons.com/image/army_valorous_unit_award_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Army Meritorious Unit Commendation Ribbon', url: 'https://www.uniformribbons.com/image/army_meritorious_unit_commendation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Army Superior Unit Award Ribbon', url: 'https://www.uniformribbons.com/image/army_superior_unit_award_ribbon.png' },
  { country: 'United States', branch: 'US Commemorative', name: 'Prisoner of War Ribbon', url: 'https://www.uniformribbons.com/image/prisoner_of_war_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Army Good Conduct Ribbon', url: 'https://www.uniformribbons.com/image/army_good_conduct_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Army Reserve Components Achievement Ribbon', url: 'https://www.uniformribbons.com/image/army_reserve_components_achievement_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'National Defense Service Medal Ribbon', url: 'https://www.uniformribbons.com/image/national_defense_service_medal_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Antarctica Service Ribbon', url: 'https://www.uniformribbons.com/image/antarctica_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Armed Forces Expeditionary Medal Ribbon', url: 'https://www.uniformribbons.com/image/armed_forces_expeditionary_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Southwest Asia Service Medal Ribbon', url: 'https://www.uniformribbons.com/image/southwest_asia_service_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Kosovo Campaign Medal Ribbon', url: 'https://www.uniformribbons.com/image/kosovo_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Afghanistan Campaign Medal Ribbon', url: 'https://www.uniformribbons.com/image/afghanistan_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Iraq Campaign Medal Ribbon', url: 'https://www.uniformribbons.com/image/iraq_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Inherent Resolve Campaign Medal', url: 'https://www.uniformribbons.com/image/inherent_resolve_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Global War on Terrorism Expeditionary Ribbon', url: 'https://www.uniformribbons.com/image/global_war_on_terrorism_expeditionary_ribbon.png' },
  { country: 'United States', branch: 'US Commemorative', name: 'Global War Terrorism Service Ribbon', url: 'https://www.uniformribbons.com/image/global_war_terrorism_service_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Korea Defense Service Medal Ribbon', url: 'https://www.uniformribbons.com/image/korea_defense_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Armed Forces Service Ribbon', url: 'https://www.uniformribbons.com/image/armed_forces_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Humanitarian Service Medal Ribbon', url: 'https://www.uniformribbons.com/image/humanitarian_service_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Outstanding Volunteer Ribbon', url: 'https://www.uniformribbons.com/image/outstanding_volunteer_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Army Sea Duty Ribbon', url: 'https://www.uniformribbons.com/image/army_sea_duty_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Armed Forces Reserve Ribbon', url: 'https://www.uniformribbons.com/image/armed_forces_reserve_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'NCO Professional Development Ribbon', url: 'https://www.uniformribbons.com/image/nco_professional_development_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Army Service Ribbon', url: 'https://www.uniformribbons.com/image/army_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Arctic Service Ribbon', url: 'https://www.uniformribbons.com/image/army_arctic_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Army Overseas Service Ribbon', url: 'https://www.uniformribbons.com/image/army_overseas_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Army Reserve Componenets Overseas Training', url: 'https://www.uniformribbons.com/image/army_reserve_components_overseas_training_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Kuwait Liberation Saudi Arabia Ribbon', url: 'https://www.uniformribbons.com/image/kuwait_liberation_saudi_arabia_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Kuwait Liberation Kuwait Ribbon', url: 'https://www.uniformribbons.com/image/kuwait_liberation_kuwait_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Kuwait Liberation Medal (Saudi Arabia) Ribbon', url: 'https://www.uniformribbons.com/image/kuwait_liberation_saudi_arabia_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Kuwait Liberation Medal (Kuwait) Ribbon', url: 'https://www.uniformribbons.com/image/kuwait_liberation_kuwait_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Navy Cross Ribbon', url: 'https://www.uniformribbons.com/image/navy_cross_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Navy Distinguished Service Ribbon', url: 'https://www.uniformribbons.com/image/navy_distinguished_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Marine Corps Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Navy Marine Corps Commendation Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_commendation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Navy Marine Corps Achievement Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_achievement_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Navy Marine Corps Combat Action Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_combat_action_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Navy Marine Corps Presidential Unit Citation Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_presidential_unit_citation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Navy Unit Commendation Ribbon', url: 'https://www.uniformribbons.com/image/navy_unit_commendation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Navy Meritorious Unit Commendation Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_meritorious_unit_commendation_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy E Ribbon', url: 'https://www.uniformribbons.com/image/navy_e_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Good Conduct Ribbon', url: 'https://www.uniformribbons.com/image/navy_good_conduct_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Naval Reserve Meritorious Service Ribbon', url: 'https://www.uniformribbons.com/image/naval_reserve_meritorious_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Navy Fleet Marine Force Ribbon', url: 'https://www.uniformribbons.com/image/navy_fleet_marine_force_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Navy Expeditionary Ribbon', url: 'https://www.uniformribbons.com/image/navy_expeditionary_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'National Defense Service Ribbon', url: 'https://www.uniformribbons.com/image/national_defense_service_medal_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Armed Forces Expeditionary Ribbon', url: 'https://www.uniformribbons.com/image/armed_forces_expeditionary_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Southwest Asia Service Ribbon', url: 'https://www.uniformribbons.com/image/southwest_asia_service_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Kosovo Campaign Ribbon', url: 'https://www.uniformribbons.com/image/kosovo_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Afghanistan Campaign Ribbon', url: 'https://www.uniformribbons.com/image/afghanistan_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Iraq Campaign Ribbon', url: 'https://www.uniformribbons.com/image/iraq_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Korea Defense Service Ribbon', url: 'https://www.uniformribbons.com/image/korea_defense_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Humanitarian Service Ribbon', url: 'https://www.uniformribbons.com/image/humanitarian_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Navy Sea Service Deployment Ribbon', url: 'https://www.uniformribbons.com/image/navy_sea_service_deployment_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Navy Reserve Sea Service Ribbon', url: 'https://www.uniformribbons.com/image/navy_reserve_sea_service_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Navy Marine Corps Overseas Service Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_overseas_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Recruiting Service Ribbon', url: 'https://www.uniformribbons.com/image/navy_recruiting_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Recruit Training Service Ribbon', url: 'https://www.uniformribbons.com/image/navy_recruit_training_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Ceremonial Guard Ribbon', url: 'https://www.uniformribbons.com/image/navy_ceremonial_guard_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Recruit Honor Graduate Ribbon', url: 'https://www.uniformribbons.com/image/navy_recruit_honor_graduate_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Navy Reserve Ribbon', url: 'https://www.uniformribbons.com/image/navy_reserve_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Rifleman Ribbon', url: 'https://www.uniformribbons.com/image/navy_rifleman_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Navy Pistol Ribbon', url: 'https://www.uniformribbons.com/image/navy_pistol_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Navy Marine Corps Medal Ribbon', url: 'https://www.uniformribbons.com/image/navy_marine_corps_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Marine Corps Good Conduct Ribbon', url: 'https://www.uniformribbons.com/image/marine_corps_good_conduct_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Selected Marine Corps Reserve Ribbon', url: 'https://www.uniformribbons.com/image/selected_marine_corps_reserve_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Marine Corps Expeditionary Ribbon', url: 'https://www.uniformribbons.com/image/marine_corps_expeditionary_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Marine Corps Recruiter Ribbon', url: 'https://www.uniformribbons.com/image/marine_corps_recruiting_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Marine Corps Drill Instructor Ribbon', url: 'https://www.uniformribbons.com/image/marine_corps_drill_instructor_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Marine Corps Security Guard Ribbon', url: 'https://www.uniformribbons.com/image/marine_corps_security_guard_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Marine Corps Combat Instructor Ribbon', url: 'https://www.uniformribbons.com/image/marine_corps_combat_instructor_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Marine Corps Reserve Ribbon', url: 'https://www.uniformribbons.com/image/marine_corps_reserve_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Kuwait Liberation Saudi Arabia', url: 'https://www.uniformribbons.com/image/kuwait_liberation_saudi_arabia_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Air Force Cross Ribbon', url: 'https://www.uniformribbons.com/image/air_force_cross_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Air Force Distinguished Service Ribbon', url: 'https://www.uniformribbons.com/image/air_force_distinguished_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Airman Ribbon', url: 'https://www.uniformribbons.com/image/airman_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Ribbon', url: 'https://www.uniformribbons.com/image/air_medal_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Aerial Achievement Ribbon', url: 'https://www.uniformribbons.com/image/aerial_achievement_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Commendation Ribbon', url: 'https://www.uniformribbons.com/image/air_force_commendation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Achievement Ribbon', url: 'https://www.uniformribbons.com/image/air_force_achievement_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Air Force Combat Action Ribbon', url: 'https://www.uniformribbons.com/image/air_force_combat_action_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Presidential Unit Citation Ribbon', url: 'https://www.uniformribbons.com/image/air_force_presidential_unit_citation_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Joint Meritorious Unit Award Ribbon', url: 'https://www.uniformribbons.com/image/joint_service_meritorious_unit_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Gallant Unit Citation Ribbon', url: 'https://www.uniformribbons.com/image/air_force_gallant_unit_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Meritorious Unit Award Ribbon', url: 'https://www.uniformribbons.com/image/air_force_meritorious_unit_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Outstanding Unit Award Ribbon', url: 'https://www.uniformribbons.com/image/air_force_outstanding_unit_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Organizational Excellence Award Ribbon', url: 'https://www.uniformribbons.com/image/air_force_organizational_excellence_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force Combat Readiness Ribbon', url: 'https://www.uniformribbons.com/image/air_force_combat_readiness_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force Good Conduct Ribbon', url: 'https://www.uniformribbons.com/image/air_force_good_conduct_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Air Reserve Meritorious Service Ribbon', url: 'https://www.uniformribbons.com/image/air_reserve_meritorious_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Outstanding Airman of the Year Ribbon', url: 'https://www.uniformribbons.com/image/outstanding_airman_of_the_year_ribbon.png' },
  { country: 'United States', branch: 'US Commendations', name: 'Air Force Recognition Ribbon', url: 'https://www.uniformribbons.com/image/air_force_recognition_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Air and Space Campaign Ribbon', url: 'https://www.uniformribbons.com/image/air_and_space_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Nuclear Deterrence Operations Service Medal', url: 'https://www.uniformribbons.com/image/air_force_nuclear_deterrence_operations_service_ribbon.png' },
  { country: 'United States', branch: 'US Campaign Medals', name: 'Remote Combat Effects Campaign Medal', url: 'https://www.uniformribbons.com/image/remote_combat_effects_campaign_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Air Force Overseas Short Service Ribbon', url: 'https://www.uniformribbons.com/image/air_force_overseas_short_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Air Force Overseas Long Service Ribbon', url: 'https://www.uniformribbons.com/image/air_force_overseas_long_ribbon.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Air Force Expeditionary Service Ribbon With Gold Frame', url: 'https://www.uniformribbons.com/image/air_force_expeditionary_service_ribbon_gold_frame.png' },
  { country: 'United States', branch: 'US Service Medals', name: 'Air Force Expeditionary Service Ribbon', url: 'https://www.uniformribbons.com/image/air_force_expeditionary_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force Longetivity Service Ribbon', url: 'https://www.uniformribbons.com/image/air_force_longetivity_service_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force Special Duty Ribbon', url: 'https://www.uniformribbons.com/image/air_force_special_duty_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force Basic Military Training Instructor Ribbon', url: 'https://www.uniformribbons.com/image/air_force_basic_military_training_instructor_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force Recruiter Ribbon', url: 'https://www.uniformribbons.com/image/air_force_recruiter_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Non-Commissioned Officer Professional Development Ribbon', url: 'https://www.uniformribbons.com/image/noncommissioned_officer_professional_development_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force BMT Honor Graduate Ribbon', url: 'https://www.uniformribbons.com/image/air_force_BMT_honor_graduate_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Small Arms Expert Marksmanship Ribbon', url: 'https://www.uniformribbons.com/image/small_arms_expert_marksmanship_ribbon.png' },
  { country: 'United States', branch: 'US Long Service', name: 'Air Force Training Ribbon', url: 'https://www.uniformribbons.com/image/air_force_training_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Air Force Distinguished Service Medal Ribbon', url: 'https://www.uniformribbons.com/image/air_force_distinguished_service_ribbon.png' },
  { country: 'United States', branch: 'US Gallantry', name: 'Airman Medal Ribbon', url: 'https://www.uniformribbons.com/image/airman_ribbon.png' },
  { country: 'United States', branch: 'US Orders & Distinguished Service', name: 'Air Reserve Meritorious Service Medal Ribbon', url: 'https://www.uniformribbons.com/image/air_reserve_meritorious_service_ribbon.png' },
];