// ─── RIBBON LIBRARY ─────────────────────────────────────────────────────────
// Sources:
//   - EZRackBuilder / USAMM — 1118 real US awards, all branches + auxiliaries
//   - medals.org.uk — 1274 international awards across 31 countries + UN
// Total: 215 ribbons. Auto-generated. DO NOT hand-edit.

export interface RibbonTemplate {
  country: string;
  branch: string;
  name: string;
  url: string;
  sku?: string;
}

export const RIBBON_COUNTRIES: string[] = ['United States', 'NATO', 'United Nations', 'United Kingdom', 'Australia', 'Canada', 'New Zealand', 'Belgium', 'France', 'Italy', 'Greece', 'Norway', 'Netherlands', 'Russia', 'Poland', 'Luxembourg'];

export const RIBBON_BRANCHES_BY_COUNTRY: Record<string, string[]> = {
  'United States': ['US Army', 'US Navy', 'US Marine Corps', 'US Air Force'],
  'United Nations': ['United Nations'],
  'NATO': ['NATO'],
  'United Kingdom': ['UK Gallantry', 'UK Orders', 'UK Commendations', 'UK Campaign Medals', 'UK Service Medals', 'UK Jubilee Medals'],
  'Australia': ['Australia Gallantry', 'Australia Orders', 'Australia Commendations', 'Australia Campaign Medals', 'Australia Service Medals', 'Australia Jubilee & Commemorative'],
  'Canada': ['Canada Gallantry', 'Canada Orders', 'Canada Campaign Medals', 'Canada Service Medals', 'Canada Jubilee & Commemorative'],
  'New Zealand': ['New Zealand Gallantry', 'New Zealand Orders', 'New Zealand Campaign Medals', 'New Zealand Service Medals', 'New Zealand Jubilee & Commemorative'],
  'Belgium': ['Belgium Orders', 'Belgium Gallantry & Crosses', 'Belgium Campaign Medals'],
  'France': ['France Orders', 'France Gallantry & Crosses', 'France Campaign Medals'],
  'Italy': ['Italy Orders', 'Italy Gallantry & Crosses', 'Italy Campaign Medals'],
  'Greece': ['Greece Orders', 'Greece Gallantry & Crosses', 'Greece Campaign Medals'],
  'Norway': ['Norway Orders', 'Norway Gallantry & Crosses', 'Norway Campaign Medals'],
  'Netherlands': ['Netherlands Orders', 'Netherlands Gallantry & Crosses', 'Netherlands Campaign Medals'],
  'Russia': ['Russia Orders'],
  'Poland': ['Poland Orders', 'Poland Gallantry & Crosses'],
  'Luxembourg': ['Luxembourg Orders', 'Luxembourg Gallantry & Crosses'],
};

export const RIBBON_TEMPLATES: RibbonTemplate[] = [
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Aerial Achievement', url: 'https://i.ezr.io/products3/400_AFAAMR.jpg?h=36&w=132&auto=format', sku: '400 AFAAMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Combat Action', url: 'https://i.ezr.io/products3/639.jpg?h=36&w=132&auto=format', sku: '639' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Cross', url: 'https://i.ezr.io/products3/405_AFCMR.jpg?h=36&w=132&auto=format', sku: '405 AFCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Distinguished Service', url: 'https://i.ezr.io/products3/406_AFAFDSMR.jpg?h=36&w=132&auto=format', sku: '406 AFAFDSMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Good Conduct', url: 'https://i.ezr.io/products3/409_AFGCMR.jpg?h=36&w=132&auto=format', sku: '409 AFGCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Meritorious Unit Award', url: 'https://i.ezr.io/products3/411_AFMUAR.jpg?h=36&w=132&auto=format', sku: '411 AFMUAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force NCO Professional Military Education Graduate', url: 'https://i.ezr.io/products3/528_AFNCOPMEGR.jpg?h=36&w=132&auto=format', sku: '528 AFNCOPMEGR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Nuclear Deterrence Operations ', url: 'https://i.ezr.io/products3/84370.jpg?h=36&w=132&auto=format', sku: '84370' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Presidential Unit Citation', url: 'https://i.ezr.io/products3/416_AFPUCR.jpg?h=36&w=132&auto=format', sku: '416 AFPUCR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Recruiting', url: 'https://i.ezr.io/products3/418_AFRECR.jpg?h=36&w=132&auto=format', sku: '418 AFRECR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Remote Combat Effects Campaign', url: 'https://i.ezr.io/products3/85495.jpg?h=36&w=132&auto=format', sku: '85495' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Special Duty', url: 'https://i.ezr.io/products3/81166.jpg?h=36&w=132&auto=format', sku: '81166' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Training', url: 'https://i.ezr.io/products3/419_AFTR.jpg?h=36&w=132&auto=format', sku: '419 AFTR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Reserve Meritorious Service', url: 'https://i.ezr.io/products3/421_AFARMSMR.jpg?h=36&w=132&auto=format', sku: '421 AFARMSMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Achievement', url: 'https://i.ezr.io/products3/403_AFAFAMR.jpg?h=36&w=132&auto=format', sku: '403 AFAFAMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Campaign', url: 'https://i.ezr.io/products3/402_AFASCMR.jpg?h=36&w=132&auto=format', sku: '402 AFASCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Commendation', url: 'https://i.ezr.io/products3/404_AFAFCMR.jpg?h=36&w=132&auto=format', sku: '404 AFAFCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Expeditionary Service', url: 'https://i.ezr.io/products3/407_AFAFESR.jpg?h=36&w=132&auto=format', sku: '407 AFAFESR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Expeditionary With Gold Frame', url: 'https://i.ezr.io/products3/408_AFERGFR.jpg?h=36&w=132&auto=format', sku: '408 AFERGFR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Longevity Service Award', url: 'https://i.ezr.io/products3/410_AFLSAR.jpg?h=36&w=132&auto=format', sku: '410 AFLSAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Organizational Excellence Award', url: 'https://i.ezr.io/products3/412_AFOEAR.jpg?h=36&w=132&auto=format', sku: '412 AFOEAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Outstanding Unit Award', url: 'https://i.ezr.io/products3/413_AFOUAR.jpg?h=36&w=132&auto=format', sku: '413 AFOUAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Overseas  Long Tour', url: 'https://i.ezr.io/products3/414_AFORLTR.jpg?h=36&w=132&auto=format', sku: '414 AFORLTR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Overseas  Short Tour', url: 'https://i.ezr.io/products3/415_AFORSTR.jpg?h=36&w=132&auto=format', sku: '415 AFORSTR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Recognition', url: 'https://i.ezr.io/products3/417_AFRR.jpg?h=36&w=132&auto=format', sku: '417 AFRR' },
  { country: 'United States', branch: 'US Air Force', name: 'Airmans', url: 'https://i.ezr.io/products3/422_AFAMR.jpg?h=36&w=132&auto=format', sku: '422 AFAMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Armed Forces Reserve Air Force', url: 'https://i.ezr.io/products3/427_AF.jpg?h=36&w=132&auto=format', sku: '427 AF' },
  { country: 'United States', branch: 'US Air Force', name: 'Basic Military Training Honor Graduate (Air Force)', url: 'https://i.ezr.io/products3/441_AFBMTHGR.jpg?h=36&w=132&auto=format', sku: '441 AFBMTHGR' },
  { country: 'United States', branch: 'US Air Force', name: 'Combat Readiness', url: 'https://i.ezr.io/products3/462_AFCRMR.jpg?h=36&w=132&auto=format', sku: '462 AFCRMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Gallant Unit Citation', url: 'https://i.ezr.io/products3/477_AFGUCR.jpg?h=36&w=132&auto=format', sku: '477 AFGUCR' },
  { country: 'United States', branch: 'US Air Force', name: 'LA F.E. Herbert Meritorious Unit Commendation (with USAF frame)', url: 'https://i.ezr.io/products3/7658LAUSAFGF.jpg?h=36&w=132&auto=format', sku: '7658LAUSAFGF' },
  { country: 'United States', branch: 'US Air Force', name: 'Military Training Instructor', url: 'https://i.ezr.io/products3/499_AFMTIR.jpg?h=36&w=132&auto=format', sku: '499 AFMTIR' },
  { country: 'United States', branch: 'US Air Force', name: 'Outstanding Airman of the Year', url: 'https://i.ezr.io/products3/530_AFOAOTYR.jpg?h=36&w=132&auto=format', sku: '530 AFOAOTYR' },
  { country: 'United States', branch: 'US Air Force', name: 'Small Arms Expert Marksmanship', url: 'https://i.ezr.io/products3/574_AFSAEMR.jpg?h=36&w=132&auto=format', sku: '574 AFSAEMR' },
  { country: 'United States', branch: 'US Air Force', name: 'United States Air Force Commemorative', url: 'https://i.ezr.io/products3/84348.jpg?h=36&w=132&auto=format', sku: '84348' },
  { country: 'United States', branch: 'US Army', name: 'Afghanistan Campaign', url: 'https://i.ezr.io/products3/401_ARACMR.jpg?h=36&w=132&auto=format', sku: '401 ARACMR' },
  { country: 'United States', branch: 'US Army', name: 'Air', url: 'https://i.ezr.io/products3/420_ARAMR.jpg?h=36&w=132&auto=format', sku: '420 ARAMR' },
  { country: 'United States', branch: 'US Army', name: 'American Campaign', url: 'https://i.ezr.io/products3/423_ARCAMR.jpg?h=36&w=132&auto=format', sku: '423 ARCAMR' },
  { country: 'United States', branch: 'US Army', name: 'American Defense', url: 'https://i.ezr.io/products3/424_ARDMR.jpg?h=36&w=132&auto=format', sku: '424 ARDMR' },
  { country: 'United States', branch: 'US Army', name: 'Antarctica Service', url: 'https://i.ezr.io/products3/425_ARASMR.jpg?h=36&w=132&auto=format', sku: '425 ARASMR' },
  { country: 'United States', branch: 'US Army', name: 'Armed Forces Expeditionary', url: 'https://i.ezr.io/products3/426_AREMR.jpg?h=36&w=132&auto=format', sku: '426 AREMR' },
  { country: 'United States', branch: 'US Army', name: 'Armed Forces Reserve Army', url: 'https://i.ezr.io/products3/427_ARRMR.jpg?h=36&w=132&auto=format', sku: '427 ARRMR' },
  { country: 'United States', branch: 'US Army', name: 'Armed Forces Service', url: 'https://i.ezr.io/products3/428_ARSMR.jpg?h=36&w=132&auto=format', sku: '428 ARSMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Achievement', url: 'https://i.ezr.io/products3/429_ARACHMR.jpg?h=36&w=132&auto=format', sku: '429 ARACHMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Commanders Award for Public Service', url: 'https://i.ezr.io/products3/609_ARM-COMM-PUB.jpg?h=36&w=132&auto=format', sku: '609 ARM-COMM-PUB' },
  { country: 'United States', branch: 'US Army', name: 'Army Commendation', url: 'https://i.ezr.io/products3/430_ARCMR.jpg?h=36&w=132&auto=format', sku: '430 ARCMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Distinguished Service', url: 'https://i.ezr.io/products3/592_ARMYDIST.jpg?h=36&w=132&auto=format', sku: '592 ARMYDIST' },
  { country: 'United States', branch: 'US Army', name: 'Army Distinguished Service Cross', url: 'https://i.ezr.io/products3/472_ARDSCR.jpg?h=36&w=132&auto=format', sku: '472 ARDSCR' },
  { country: 'United States', branch: 'US Army', name: 'Army Exceptional Public Service', url: 'https://i.ezr.io/products3/612_ARM-EXCP-PUB.jpg?h=36&w=132&auto=format', sku: '612 ARM-EXCP-PUB' },
  { country: 'United States', branch: 'US Army', name: 'Army Good Conduct', url: 'https://i.ezr.io/products3/431_ARGCMR.jpg?h=36&w=132&auto=format', sku: '431 ARGCMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Meritorious Honor Award', url: 'https://i.ezr.io/products3/613.jpg?h=36&w=132&auto=format', sku: '613' },
  { country: 'United States', branch: 'US Army', name: 'Army Meritorious Unit Citation', url: 'https://i.ezr.io/products3/432_ARMUCR.jpg?h=36&w=132&auto=format', sku: '432 ARMUCR' },
  { country: 'United States', branch: 'US Army', name: 'Army NCO Professional Development', url: 'https://i.ezr.io/products3/529_ARNONCOPDR.jpg?h=36&w=132&auto=format', sku: '529 ARNONCOPDR' },
  { country: 'United States', branch: 'US Army', name: 'Army Overseas Service', url: 'https://i.ezr.io/products3/433_AROSR.jpg?h=36&w=132&auto=format', sku: '433 AROSR' },
  { country: 'United States', branch: 'US Army', name: 'Army Presidential Unit Citation', url: 'https://i.ezr.io/products3/434_ARPUCR.jpg?h=36&w=132&auto=format', sku: '434 ARPUCR' },
  { country: 'United States', branch: 'US Army', name: 'Army Recruiting', url: 'https://i.ezr.io/products3/85786.jpg?h=36&w=132&auto=format', sku: '85786' },
  { country: 'United States', branch: 'US Army', name: 'Army Reserve Components Achievement', url: 'https://i.ezr.io/products3/435_ARRRCAMR.jpg?h=36&w=132&auto=format', sku: '435 ARRRCAMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Reserve Components Overseas Training', url: 'https://i.ezr.io/products3/568_ARRCOTR.jpg?h=36&w=132&auto=format', sku: '568 ARRCOTR' },
  { country: 'United States', branch: 'US Army', name: 'Army Sea Duty', url: 'https://i.ezr.io/products3/643.jpg?h=36&w=132&auto=format', sku: '643' },
  { country: 'United States', branch: 'US Army', name: 'Army Service', url: 'https://i.ezr.io/products3/436_ARSR.jpg?h=36&w=132&auto=format', sku: '436 ARSR' },
  { country: 'United States', branch: 'US Army', name: 'Army Soldiers  - Heroism', url: 'https://i.ezr.io/products3/437_ARSMHR.jpg?h=36&w=132&auto=format', sku: '437 ARSMHR' },
  { country: 'United States', branch: 'US Army', name: 'Army Superior Unit Award', url: 'https://i.ezr.io/products3/438_ARSUAR.jpg?h=36&w=132&auto=format', sku: '438 ARSUAR' },
  { country: 'United States', branch: 'US Army', name: 'Army Valorous Unit Citation Award', url: 'https://i.ezr.io/products3/439_ARVUCAR.jpg?h=36&w=132&auto=format', sku: '439 ARVUCAR' },
  { country: 'United States', branch: 'US Army', name: 'Belgian Croix de Guerre', url: 'https://i.ezr.io/products3/589_BELGCROIX.jpg?h=36&w=132&auto=format', sku: '589 BELGCROIX' },
  { country: 'United States', branch: 'US Army', name: 'Bronze Star', url: 'https://i.ezr.io/products3/443_ARBSR.jpg?h=36&w=132&auto=format', sku: '443 ARBSR' },
  { country: 'United States', branch: 'US Army', name: 'Cold War', url: 'https://i.ezr.io/products3/662.jpg?h=36&w=132&auto=format', sku: '662' },
  { country: 'United States', branch: 'US Army', name: 'Commandants Letter of Commendation', url: 'https://i.ezr.io/products3/463_CGCLOCR.jpg?h=36&w=132&auto=format', sku: '463 CGCLOCR' },
  { country: 'United States', branch: 'US Army', name: 'Defense Meritorious Service', url: 'https://i.ezr.io/products3/468_ARDMSMR.jpg?h=36&w=132&auto=format', sku: '468 ARDMSMR' },
  { country: 'United States', branch: 'US Army', name: 'Defense Superior Service', url: 'https://i.ezr.io/products3/469_ARDSSMR.jpg?h=36&w=132&auto=format', sku: '469 ARDSSMR' },
  { country: 'United States', branch: 'US Army', name: 'European - African - Middle Eastern Campaign', url: 'https://i.ezr.io/products3/474_AREAMECMR.jpg?h=36&w=132&auto=format', sku: '474 AREAMECMR' },
  { country: 'United States', branch: 'US Army', name: 'Global War on Terrorism Expeditionary', url: 'https://i.ezr.io/products3/478_ARGWTEMR.jpg?h=36&w=132&auto=format', sku: '478 ARGWTEMR' },
  { country: 'United States', branch: 'US Army', name: 'Global War on Terrorism Service', url: 'https://i.ezr.io/products3/479_ARGWTSMR.jpg?h=36&w=132&auto=format', sku: '479 ARGWTSMR' },
  { country: 'United States', branch: 'US Army', name: 'Gold Lifesaving', url: 'https://i.ezr.io/products3/586_GOLDLIFE.jpg?h=36&w=132&auto=format', sku: '586 GOLDLIFE' },
  { country: 'United States', branch: 'US Army', name: 'Holland 4 Days Cross Marches Nijmegen', url: 'https://i.ezr.io/products3/85175.jpg?h=36&w=132&auto=format', sku: '85175' },
  { country: 'United States', branch: 'US Army', name: 'Humanitarian Service', url: 'https://i.ezr.io/products3/480_ARHSMR.jpg?h=36&w=132&auto=format', sku: '480 ARHSMR' },
  { country: 'United States', branch: 'US Army', name: 'Inherent Resolve Campaign', url: 'https://i.ezr.io/products3/81270.jpg?h=36&w=132&auto=format', sku: '81270' },
  { country: 'United States', branch: 'US Army', name: 'Inter-American Defense Board', url: 'https://i.ezr.io/products3/481_ARIADBMR.jpg?h=36&w=132&auto=format', sku: '481 ARIADBMR' },
  { country: 'United States', branch: 'US Army', name: 'International March of Diekirch', url: 'https://i.ezr.io/products3/85785.jpg?h=36&w=132&auto=format', sku: '85785' },
  { country: 'United States', branch: 'US Army', name: 'Iraq Campaign', url: 'https://i.ezr.io/products3/482_ARICMR.jpg?h=36&w=132&auto=format', sku: '482 ARICMR' },
  { country: 'United States', branch: 'US Army', name: 'Joint Meritorious Unit Award with Army Frame', url: 'https://i.ezr.io/products3/484_ARJMUAR.jpg?h=36&w=132&auto=format', sku: '484 ARJMUAR' },
  { country: 'United States', branch: 'US Army', name: 'Joint Service Achievement', url: 'https://i.ezr.io/products3/485_ARJSAMR.jpg?h=36&w=132&auto=format', sku: '485 ARJSAMR' },
  { country: 'United States', branch: 'US Army', name: 'Joint Service Commendation', url: 'https://i.ezr.io/products3/486_ARJSCMR.jpg?h=36&w=132&auto=format', sku: '486 ARJSCMR' },
  { country: 'United States', branch: 'US Army', name: 'Korea Defense Service', url: 'https://i.ezr.io/products3/486-A_ARKDSMR.jpg?h=36&w=132&auto=format', sku: '486-A ARKDSMR' },
  { country: 'United States', branch: 'US Army', name: 'Kosovo Campaign', url: 'https://i.ezr.io/products3/488_ARKCMR.jpg?h=36&w=132&auto=format', sku: '488 ARKCMR' },
  { country: 'United States', branch: 'US Army', name: 'Kuwait Liberation of Kuwait', url: 'https://i.ezr.io/products3/489_ARKLMKR.jpg?h=36&w=132&auto=format', sku: '489 ARKLMKR' },
  { country: 'United States', branch: 'US Army', name: 'Legion of Merit', url: 'https://i.ezr.io/products3/490_ARLOFR.jpg?h=36&w=132&auto=format', sku: '490 ARLOFR' },
  { country: 'United States', branch: 'US Army', name: 'Legion of Merit Officer', url: 'https://i.ezr.io/products3/640.jpg?h=36&w=132&auto=format', sku: '640' },
  { country: 'United States', branch: 'US Army', name: 'Meritorious Service', url: 'https://i.ezr.io/products3/498_ARMSMR.jpg?h=36&w=132&auto=format', sku: '498 ARMSMR' },
  { country: 'United States', branch: 'US Army', name: 'Mexican Service - Army', url: 'https://i.ezr.io/products3/594_MEX-SVC-RBARMY.jpg?h=36&w=132&auto=format', sku: '594 MEX-SVC-RBARMY' },
  { country: 'United States', branch: 'US Army', name: 'Multi-National Forces and Observers', url: 'https://i.ezr.io/products3/500_ARMNFOMR.jpg?h=36&w=132&auto=format', sku: '500 ARMNFOMR' },
  { country: 'United States', branch: 'US Army', name: 'NATO', url: 'https://i.ezr.io/products3/504.jpg?h=36&w=132&auto=format', sku: '504' },
  { country: 'United States', branch: 'US Army', name: 'NATO Article 5 Active Endeavour', url: 'https://i.ezr.io/products3/654.jpg?h=36&w=132&auto=format', sku: '654' },
  { country: 'United States', branch: 'US Army', name: 'NATO ISAF (International Security Assistance Force)', url: 'https://i.ezr.io/products3/637_NATO-ISAF-R.jpg?h=36&w=132&auto=format', sku: '637 NATO-ISAF-R' },
  { country: 'United States', branch: 'US Army', name: 'NATO Kosovo', url: 'https://i.ezr.io/products3/503_ARNATOKMR.jpg?h=36&w=132&auto=format', sku: '503 ARNATOKMR' },
  { country: 'United States', branch: 'US Army', name: 'NATO Meritorious Service', url: 'https://i.ezr.io/products3/653.jpg?h=36&w=132&auto=format', sku: '653' },
  { country: 'United States', branch: 'US Army', name: 'NATO NTM-IRAQ (NATO Training Mission Iraq)', url: 'https://i.ezr.io/products3/637.jpg?h=36&w=132&auto=format', sku: '637' },
  { country: 'United States', branch: 'US Army', name: 'NATO Non-Article 5', url: 'https://i.ezr.io/products3/637_NATO-NA5.jpg?h=36&w=132&auto=format', sku: '637 NATO-NA5' },
  { country: 'United States', branch: 'US Army', name: 'NATO Non-Article 5 for the Balkans', url: 'https://i.ezr.io/products3/641.jpg?h=36&w=132&auto=format', sku: '641' },
  { country: 'United States', branch: 'US Army', name: 'NATO Operation Resolute Support', url: 'https://i.ezr.io/products3/637_NATO-ORS.jpg?h=36&w=132&auto=format', sku: '637 NATO-ORS' },
  { country: 'United States', branch: 'US Army', name: 'National Defense Service', url: 'https://i.ezr.io/products3/501_ARNDSMR.jpg?h=36&w=132&auto=format', sku: '501 ARNDSMR' },
  { country: 'United States', branch: 'US Army', name: 'Philippine Independence', url: 'https://i.ezr.io/products3/533_ARPIMR.jpg?h=36&w=132&auto=format', sku: '533 ARPIMR' },
  { country: 'United States', branch: 'US Army', name: 'Philippine Presidential Unit Citation with Army Frame', url: 'https://i.ezr.io/products3/536_ARPPUCR.jpg?h=36&w=132&auto=format', sku: '536 ARPPUCR' },
  { country: 'United States', branch: 'US Army', name: 'Presidential Inauguration Support', url: 'https://i.ezr.io/products3/85996.jpg?h=36&w=132&auto=format', sku: '85996' },
  { country: 'United States', branch: 'US Army', name: 'Prisoner of War', url: 'https://i.ezr.io/products3/538_ARPOWMR.jpg?h=36&w=132&auto=format', sku: '538 ARPOWMR' },
  { country: 'United States', branch: 'US Army', name: 'Purple Heart', url: 'https://i.ezr.io/products3/539_ARPHR.jpg?h=36&w=132&auto=format', sku: '539 ARPHR' },
  { country: 'United States', branch: 'US Army', name: 'Republic of Korea Presidential Unit Citation with Army Frame', url: 'https://i.ezr.io/products3/542_ARRKPCR.jpg?h=36&w=132&auto=format', sku: '542 ARRKPCR' },
  { country: 'United States', branch: 'US Army', name: 'Saudi Arabian  for the Liberation of Kuwait', url: 'https://i.ezr.io/products3/571_ARSAMLKR.jpg?h=36&w=132&auto=format', sku: '571 ARSAMLKR' },
  { country: 'United States', branch: 'US Army', name: 'Silver Lifesaving', url: 'https://i.ezr.io/products3/587_SILVLIFE.jpg?h=36&w=132&auto=format', sku: '587 SILVLIFE' },
  { country: 'United States', branch: 'US Army', name: 'Silver Star', url: 'https://i.ezr.io/products3/573_ARSSMR.jpg?h=36&w=132&auto=format', sku: '573 ARSSMR' },
  { country: 'United States', branch: 'US Army', name: 'Southwest Asia Service', url: 'https://i.ezr.io/products3/575_ARSWASMR.jpg?h=36&w=132&auto=format', sku: '575 ARSWASMR' },
  { country: 'United States', branch: 'US Army', name: 'United Nations', url: 'https://i.ezr.io/products3/579_ARUNMR.jpg?h=36&w=132&auto=format', sku: '579 ARUNMR' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Advance Mission in Cambodia ', url: 'https://i.ezr.io/products3/646.jpg?h=36&w=132&auto=format', sku: '646' },
  { country: 'United States', branch: 'US Army', name: 'United Nations In Service of Peace Commemorative', url: 'https://i.ezr.io/products3/84342.jpg?h=36&w=132&auto=format', sku: '84342' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Mission in Haiti', url: 'https://i.ezr.io/products3/645.jpg?h=36&w=132&auto=format', sku: '645' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Operation in Somalia (UNOSOM)', url: 'https://i.ezr.io/products3/644.jpg?h=36&w=132&auto=format', sku: '644' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Protection Force (UNPROFOR)', url: 'https://i.ezr.io/products3/81047.jpg?h=36&w=132&auto=format', sku: '81047' },
  { country: 'United States', branch: 'US Army', name: 'United States Army Commemorative', url: 'https://i.ezr.io/products3/84349.jpg?h=36&w=132&auto=format', sku: '84349' },
  { country: 'United States', branch: 'US Army', name: 'Womens Army Corps Service', url: 'https://i.ezr.io/products3/581_ARWACSMR.jpg?h=36&w=132&auto=format', sku: '581 ARWACSMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Armed Forces Reserve Marine Corps', url: 'https://i.ezr.io/products3/427_MC.jpg?h=36&w=132&auto=format', sku: '427 MC' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps China Service', url: 'https://i.ezr.io/products3/444_MCCSMR.jpg?h=36&w=132&auto=format', sku: '444 MCCSMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Combat Instructor', url: 'https://i.ezr.io/products3/83998.jpg?h=36&w=132&auto=format', sku: '83998' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Drill Instructor', url: 'https://i.ezr.io/products3/491_MCMCDIR.jpg?h=36&w=132&auto=format', sku: '491 MCMCDIR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Expeditionary', url: 'https://i.ezr.io/products3/492_MCEMR.jpg?h=36&w=132&auto=format', sku: '492 MCEMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Good Conduct', url: 'https://i.ezr.io/products3/493_MMCGR.jpg?h=36&w=132&auto=format', sku: '493 MMCGR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Recruiting', url: 'https://i.ezr.io/products3/495_MCRR.jpg?h=36&w=132&auto=format', sku: '495 MCRR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Reserve Service', url: 'https://i.ezr.io/products3/590_MRNRESERV.jpg?h=36&w=132&auto=format', sku: '590 MRNRESERV' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Security Guard', url: 'https://i.ezr.io/products3/496_MCSGR.jpg?h=36&w=132&auto=format', sku: '496 MCSGR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Selected Marine Corps Reserve', url: 'https://i.ezr.io/products3/572_MCSMCRMR.jpg?h=36&w=132&auto=format', sku: '572 MCSMCRMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'United States Marine Corps Commemorative', url: 'https://i.ezr.io/products3/84350.jpg?h=36&w=132&auto=format', sku: '84350' },
  { country: 'United States', branch: 'US Navy', name: 'Armed Forces Reserve Navy', url: 'https://i.ezr.io/products3/427_NAVY.jpg?h=36&w=132&auto=format', sku: '427 NAVY' },
  { country: 'United States', branch: 'US Navy', name: 'Combat Action', url: 'https://i.ezr.io/products3/461_NCAR.jpg?h=36&w=132&auto=format', sku: '461 NCAR' },
  { country: 'United States', branch: 'US Navy', name: 'Fleet Marine Force', url: 'https://i.ezr.io/products3/475_NFMFR.jpg?h=36&w=132&auto=format', sku: '475 NFMFR' },
  { country: 'United States', branch: 'US Navy', name: 'Joint Meritorious Unit Award with NAVY/AF/MC/CG Frame', url: 'https://i.ezr.io/products3/483_NJMAR.jpg?h=36&w=132&auto=format', sku: '483 NJMAR' },
  { country: 'United States', branch: 'US Navy', name: 'Naval Reserve Meritorious Service', url: 'https://i.ezr.io/products3/505_NRMSMR.jpg?h=36&w=132&auto=format', sku: '505 NRMSMR' },
  { country: 'United States', branch: 'US Navy', name: 'Naval Reserve Sea Service', url: 'https://i.ezr.io/products3/506_NRSSR.jpg?h=36&w=132&auto=format', sku: '506 NRSSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps', url: 'https://i.ezr.io/products3/509_NNMCMR.jpg?h=36&w=132&auto=format', sku: '509 NNMCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps Achievement', url: 'https://i.ezr.io/products3/507_NMCAMR.jpg?h=36&w=132&auto=format', sku: '507 NMCAMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps Commendation', url: 'https://i.ezr.io/products3/508_NMCCMR.jpg?h=36&w=132&auto=format', sku: '508 NMCCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps Overseas Service', url: 'https://i.ezr.io/products3/510_NNMOSR.jpg?h=36&w=132&auto=format', sku: '510 NNMOSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Arctic Service', url: 'https://i.ezr.io/products3/511_NASR.jpg?h=36&w=132&auto=format', sku: '511 NASR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Basic Military Training Honor Graduate', url: 'https://i.ezr.io/products3/692.jpg?h=36&w=132&auto=format', sku: '692' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Ceremonial Guard', url: 'https://i.ezr.io/products3/599_NAVCERMGD.jpg?h=36&w=132&auto=format', sku: '599 NAVCERMGD' },
  { country: 'United States', branch: 'US Navy', name: 'Navy China Service', url: 'https://i.ezr.io/products3/444_NCSMR.jpg?h=36&w=132&auto=format', sku: '444 NCSMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Cross', url: 'https://i.ezr.io/products3/512_NCMR.jpg?h=36&w=132&auto=format', sku: '512 NCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Distinguished Public Service', url: 'https://i.ezr.io/products3/620_NAV-DIST-PUB.jpg?h=36&w=132&auto=format', sku: '620 NAV-DIST-PUB' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Distinguished Service', url: 'https://i.ezr.io/products3/515_NDSMR.jpg?h=36&w=132&auto=format', sku: '515 NDSMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy E', url: 'https://i.ezr.io/products3/516_NER.jpg?h=36&w=132&auto=format', sku: '516 NER' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Expeditionary', url: 'https://i.ezr.io/products3/517_NEMR.jpg?h=36&w=132&auto=format', sku: '517 NEMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Expert Pistol', url: 'https://i.ezr.io/products3/518_NEPMR.jpg?h=36&w=132&auto=format', sku: '518 NEPMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Expert Rifleman', url: 'https://i.ezr.io/products3/519_NERR.jpg?h=36&w=132&auto=format', sku: '519 NERR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Good Conduct', url: 'https://i.ezr.io/products3/520_NGCMR.jpg?h=36&w=132&auto=format', sku: '520 NGCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Meritorious Public Service', url: 'https://i.ezr.io/products3/622_NAV-MER-PUB.jpg?h=36&w=132&auto=format', sku: '622 NAV-MER-PUB' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Meritorious Unit Commendation', url: 'https://i.ezr.io/products3/521_NMUCR.jpg?h=36&w=132&auto=format', sku: '521 NMUCR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Presidential Unit Citation', url: 'https://i.ezr.io/products3/523_NPUCR.jpg?h=36&w=132&auto=format', sku: '523 NPUCR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Recruit Training Service', url: 'https://i.ezr.io/products3/540_NRTSR.jpg?h=36&w=132&auto=format', sku: '540 NRTSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Recruiting Service', url: 'https://i.ezr.io/products3/524_NRSR.jpg?h=36&w=132&auto=format', sku: '524 NRSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Reserve', url: 'https://i.ezr.io/products3/525_NRMR.jpg?h=36&w=132&auto=format', sku: '525 NRMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Reserve Specialist Commendation', url: 'https://i.ezr.io/products3/85501.jpg?h=36&w=132&auto=format', sku: '85501' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Sea Service Deployment', url: 'https://i.ezr.io/products3/526_NSSDR.jpg?h=36&w=132&auto=format', sku: '526 NSSDR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Superior Public Service', url: 'https://i.ezr.io/products3/624_NAV-SUP-PUB.jpg?h=36&w=132&auto=format', sku: '624 NAV-SUP-PUB' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Unit Commendation', url: 'https://i.ezr.io/products3/527_NUCR.jpg?h=36&w=132&auto=format', sku: '527 NUCR' },
  { country: 'United States', branch: 'US Navy', name: 'Philippine Presidential Unit Citation - AF/N/MC/CG Frame', url: 'https://i.ezr.io/products3/537.jpg?h=36&w=132&auto=format', sku: '537' },
  { country: 'United States', branch: 'US Navy', name: 'Republic of Korea Presidential Unit Citation with Navy Frame', url: 'https://i.ezr.io/products3/543_NRKPCR.jpg?h=36&w=132&auto=format', sku: '543 NRKPCR' },
  { country: 'United States', branch: 'US Navy', name: 'United States Navy Commemorative', url: 'https://i.ezr.io/products3/84351.jpg?h=36&w=132&auto=format', sku: '84351' },
  // ─── INTERNATIONAL ───
  // ─── NATO ───
  // ─── UNITED NATIONS ───



  // === UNITED NATIONS ===
  { country: 'United Nations', branch: 'United Nations', name: 'UN Korea Medal (UNSER)', url: 'https://www.medals.pl/int/r/unser.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNEF Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations028.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTSO Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations032.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMOGIP Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations034.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'ONUC Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations033.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTEA Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations016.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNYOM Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations038.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNFICYP Medal (Cyprus)', url: 'https://www.medals.pl/int/r/unfic.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNEFME Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations045.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNDOF Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations047.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNIFIL Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations018.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNIIMOG Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations052.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTAG Medal (Namibia)', url: 'https://www.medals.pl/int/r/untag.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'ONUCA Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations057.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNIKOM Medal (Iraq/Kuwait)', url: 'https://www.medals.pl/int/r/unikom.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAVEM Medal (Angola)', url: 'https://www.medals.pl/int/r/unavem.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MINURSO Medal (Western Sahara)', url: 'https://www.medals.pl/int/r/minurso.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'ONUSAL Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations062.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNPROFOR Medal (Bosnia)', url: 'https://www.medals.pl/int/r/unprofor.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAMIC Medal (Cambodia)', url: 'https://www.medals.pl/int/r/unamic.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTAC Medal (Cambodia)', url: 'https://www.medals.pl/int/r/untac.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOSOM Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations070.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'ONUMOZ Medal (Mozambique)', url: 'https://www.medals.pl/int/r/onumoz.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAMIR Medal (Rwanda)', url: 'https://www.medals.pl/int/r/unamir.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIH Medal (Haiti)', url: 'https://www.medals.pl/int/r/unmih.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMIG Medal (Georgia)', url: 'https://www.medals.pl/int/r/unomig.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMIL Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations078.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMUR Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations079.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMOT Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations024.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIBH Medal (Bosnia)', url: 'https://www.medals.pl/int/r/unmibh.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMOP Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations083.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNTAES Medal (E. Slavonia)', url: 'https://www.medals.pl/int/r/untaes.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MINUGUA Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations006.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MINURCA Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations087.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNPSG Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations089.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNOMSIL Medal (Sierra Leone)', url: 'https://www.medals.pl/int/r/unomsil.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIK Medal (Kosovo)', url: 'https://www.medals.pl/int/r/unmik.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNAMET Medal (East Timor)', url: 'https://www.medals.pl/int/r/unamet.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNPREDEP Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations097.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'MONUC Medal (Congo)', url: 'https://www.medals.pl/int/r/monuc.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMEE Medal', url: 'https://www.medals.org.uk/united-nations/images/united-nations104.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNSSM Medal (Special Service)', url: 'https://www.medals.pl/int/r/unssm.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNHQ Medal (HQ Service)', url: 'https://www.medals.pl/int/r/unhq.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIL Medal (Liberia)', url: 'https://www.medals.pl/int/r/unmil.gif' },
  { country: 'United Nations', branch: 'United Nations', name: 'UNMIS Medal (Sudan)', url: 'https://www.medals.pl/int/r/unmis.gif' },


  // === NATO ===
  { country: 'NATO', branch: 'NATO', name: 'OSCE Medal', url: 'https://www.medals.org.uk/nato/images/nato007.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Meritorious Service Medal', url: 'https://www.medals.org.uk/nato/images/nato004.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Former Yugoslavia)', url: 'https://www.medals.pl/bc/r/nato.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Kosovo)', url: 'https://www.medals.pl/bc/r/natok.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Macedonia)', url: 'https://www.medals.pl/bc/r/natom.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Article 5 - Eagle Assist)', url: 'https://www.medals.pl/int/r/natoa5b.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Article 5 - Active Endeavour)', url: 'https://www.medals.pl/bc/r/natoa5.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (Non-Article 5 - Operations in the Balkans)', url: 'https://www.medals.pl/int/r/natob.gif' },
  { country: 'NATO', branch: 'NATO', name: 'NATO Medal (ISAF - Afghanistan)', url: 'https://www.medals.pl/bc/r/natoisaf.gif' },

  // ── United Kingdom ──────────────────────────────────────────────
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Victoria Cross (VC)', url: 'https://www.medals.pl/bc/r/uk1vc.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Conspicuous Gallantry Cross (CGC)', url: 'https://www.medals.pl/bc/r/uk1cgc.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'King\'s/Queen\'s Commendation for Bravery (KCB/QCB)', url: 'https://www.medals.pl/bc/r/uk1bqcb.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'King\'s/Queen\'s Commendation for Bravery in the Air', url: 'https://www.medals.pl/bc/r/uk1bqcba.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'King\'s/Queen\'s Commendation for Valuable Service', url: 'https://www.medals.pl/bc/r/uk1bqcvs.gif' },
  { country: 'United Kingdom', branch: 'UK Commendations', name: 'Mention in Despatches (MID)', url: 'https://www.medals.pl/bc/r/uk1bmid2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'South Atlantic Medal 1982 (Falklands)', url: 'https://www.medals.pl/bc/r/uk1msa1.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Gulf Medal 1991', url: 'https://www.medals.pl/bc/r/uk1mgu.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Operational Service Medal - Sierra Leone', url: 'https://www.medals.pl/bc/r/uk1mos_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Operational Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/uk1mosaf_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Iraq Campaign Medal 2003 (Op Telic)', url: 'https://www.medals.pl/bc/r/uk1miqc_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Operational Service Medal - Congo', url: 'https://www.medals.pl/bc/r/uk1mosco_m2.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Iraq Reconstruction Service Medal', url: 'https://www.medals.pl/bc/r/uk1mirs.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Civilian Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/uk1mcsaf.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Accumulated Campaign Service Medal (1994-2011)', url: 'https://www.medals.pl/bc/r/uk1mas.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Accumulated Campaign Service Medal (2011)', url: 'https://www.medals.pl/bc/r/uk1macb.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'King\'s/Queen\'s Volunteer Reserves Medal (KVRM/QVRM)', url: 'https://www.medals.pl/bc/r/uk1mqvr.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Volunteer Reserves Service Medal (VRSM)', url: 'https://www.medals.pl/bc/r/uk1mvrs.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Volunteer Reserves Service Medal - HAC', url: 'https://www.medals.pl/bc/r/uk1mhac.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Northern Ireland Home Service Medal', url: 'https://www.medals.pl/bc/r/uk1mhsni.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Royal Fleet Auxiliary Service Medal', url: 'https://www.medals.pl/bc/r/uk1mrfa.gif' },
  { country: 'United Kingdom', branch: 'UK Jubilee Medals', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'United Kingdom', branch: 'UK Jubilee Medals', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },

  // ── Australia ────────────────────────────────────────────────────
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Star of Gallantry (SG)', url: 'https://www.medals.pl/bc/r/au2sga.gif' },
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Medal for Gallantry (MG)', url: 'https://www.medals.pl/bc/r/au2mga.gif' },
  { country: 'Australia', branch: 'Australia Commendations', name: 'Commendation for Gallantry', url: 'https://www.medals.pl/bc/r/au2coga.gif' },
  { country: 'Australia', branch: 'Australia Commendations', name: 'Commendation for Distinguished Service', url: 'https://www.medals.pl/bc/r/au2cods.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Distinguished Service Cross (DSC)', url: 'https://www.medals.pl/bc/r/au2cds.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Conspicuous Service Cross (CSC)', url: 'https://www.medals.pl/bc/r/au2ccs.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Distinguished Service Medal (DSM)', url: 'https://www.medals.pl/bc/r/au2mds.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Conspicuous Service Medal (CSM)', url: 'https://www.medals.pl/bc/r/au2mcs.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Defence Force Long Service Medal', url: 'https://www.medals.pl/bc/r/au2mlsd.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Reserve Force Decoration (RFD)', url: 'https://www.medals.pl/bc/r/au2drf.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Reserve Force Medal', url: 'https://www.medals.pl/bc/r/au2mrf.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Defence Medal', url: 'https://www.medals.pl/bc/r/au2mad.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'Afghanistan Medal', url: 'https://www.medals.pl/bc/r/au2maf.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'Iraq Medal', url: 'https://www.medals.pl/bc/r/au2miq.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Australian Centenary Medal 2000', url: 'https://www.medals.pl/bc/r/au2mce.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Unit Citation for Gallantry', url: 'https://www.medals.pl/bc/r/au2ucga1.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Meritorious Unit Citation', url: 'https://www.medals.pl/bc/r/au2ucms1.gif' },

  // ── Canada ───────────────────────────────────────────────────────
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Star of Military Valour (SMV)', url: 'https://www.medals.pl/bc/r/ca2smv.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Medal of Military Valour (MMV)', url: 'https://www.medals.pl/bc/r/ca2mmv.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Meritorious Service Cross - Military (MSC)', url: 'https://www.medals.pl/bc/r/ca2cmsm.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Meritorious Service Medal - Military (MSM)', url: 'https://www.medals.pl/bc/r/ca2mmsm.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Gulf and Kuwait Medal', url: 'https://www.medals.pl/bc/r/ca2mgk1.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Somalia Medal', url: 'https://www.medals.pl/bc/r/ca2mso.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'South West Asia Service Medal (SWASM)', url: 'https://www.medals.pl/bc/r/ca2mswass.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Campaign Star - Afghanistan', url: 'https://www.medals.pl/bc/r/ca2sgcaf.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Campaign Star - SW Asia', url: 'https://www.medals.pl/bc/r/ca2sgcswa.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - Expedition', url: 'https://www.medals.pl/bc/r/ca2mosexp.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - SW Asia', url: 'https://www.medals.pl/bc/r/ca2mosswa.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Special Service Medal (SSM)', url: 'https://www.medals.pl/bc/r/ca2mss.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Canadian Peacekeeping Service Medal (CPSM)', url: 'https://www.medals.pl/bc/r/ca2mpe.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'Canada', branch: 'Canada Jubilee & Commemorative', name: '125th Anniversary of Confederation Medal 1992', url: 'https://www.medals.pl/bc/r/ca2m125.gif' },
  { country: 'Canada', branch: 'Canada Jubilee & Commemorative', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'Canada', branch: 'Canada Jubilee & Commemorative', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },

  // ── New Zealand ──────────────────────────────────────────────────
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'New Zealand Cross (NZC)', url: 'https://www.medals.pl/bc/r/nz2nzc.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Gallantry Star (NZGS)', url: 'https://www.medals.pl/bc/r/nz2nzgs.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Bravery Star (NZBS)', url: 'https://www.medals.pl/bc/r/nz2nzbs.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Gallantry Decoration (NZGD)', url: 'https://www.medals.pl/bc/r/nz2nzgd.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Bravery Decoration (NZBD)', url: 'https://www.medals.pl/bc/r/nz2nzbd.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Gallantry Medal (NZGM)', url: 'https://www.medals.pl/bc/r/nz2nzgm.gif' },
  { country: 'New Zealand', branch: 'New Zealand Gallantry', name: 'NZ Bravery Medal (NZBM)', url: 'https://www.medals.pl/bc/r/nz2nzbm.gif' },
  { country: 'New Zealand', branch: 'New Zealand Orders', name: 'Order of New Zealand (ONZ)', url: 'https://www.medals.pl/bc/r/nz2onz.gif' },
  { country: 'New Zealand', branch: 'New Zealand Orders', name: 'New Zealand Order of Merit', url: 'https://www.medals.pl/bc/r/nz2nzom.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'Distinguished Service Decoration (DSD)', url: 'https://www.medals.pl/bc/r/nz2dsd.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Meritorious Service Medal', url: 'https://www.medals.pl/bc/r/nz2mms.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Armed Forces Award', url: 'https://www.medals.pl/bc/r/nz2aarf.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'Operational Service Medal (NZ)', url: 'https://www.medals.pl/bc/r/nz2mos.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/nz2mgsaf.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'GSM - Afghanistan (secondary area)', url: 'https://www.medals.pl/bc/r/nz2mgsafb.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Iraq 2003', url: 'https://www.medals.pl/bc/r/nz2mgsiq.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'NZ East Timor Medal', url: 'https://www.medals.pl/bc/r/nz2met.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Solomon Islands', url: 'https://www.medals.pl/bc/r/nz2mgssi.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Timor Leste', url: 'https://www.medals.pl/bc/r/nz2mgstl.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'NZ General Service Medal (Warlike)', url: 'https://www.medals.pl/bc/r/nz2mgsw.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'NZ General Service Medal (Non-Warlike)', url: 'https://www.medals.pl/bc/r/nz2mgsp.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'International Force East Timor Medal (INTERFET)', url: 'https://www.medals.pl/bc/r/interfet.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Army LS & GC Medal', url: 'https://www.medals.pl/bc/r/uk1mlsa.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Navy LS & GC Medal', url: 'https://www.medals.pl/bc/r/uk1mlsn.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Air Force LS & GC Medal', url: 'https://www.medals.pl/bc/r/uk1mlsaf.gif' },
  { country: 'New Zealand', branch: 'New Zealand Jubilee & Commemorative', name: 'NZ Commemorative Medal 1990', url: 'https://www.medals.pl/bc/r/nz2mco90.gif' },
  { country: 'New Zealand', branch: 'New Zealand Jubilee & Commemorative', name: 'Golden Jubilee Medal 2002', url: 'https://www.medals.pl/bc/r/uk1mju2002.gif' },
  { country: 'New Zealand', branch: 'New Zealand Jubilee & Commemorative', name: 'Diamond Jubilee Medal 2012', url: 'https://www.medals.pl/bc/r/uk1mju2012.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'Special Service Medal - Asian Tsunami', url: 'https://www.medals.pl/bc/r/nz2mssat.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'George Cross (GC)', url: 'https://www.medals.pl/bc/r/uk1gc.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Distinguished Service Order (DSO)', url: 'https://www.medals.pl/bc/r/uk1ods.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Military Cross (MC)', url: 'https://www.medals.pl/bc/r/uk1cmm.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Distinguished Service Cross (DSC)', url: 'https://www.medals.pl/bc/r/uk1cds.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Distinguished Flying Cross (DFC)', url: 'https://www.medals.pl/bc/r/uk1cdfb.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Air Force Cross (AFC)', url: 'https://www.medals.pl/bc/r/uk1cafb.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'George Medal (GM)', url: 'https://www.medals.pl/bc/r/uk1mge.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Queen/King Gallantry Medal (QGM/KGM)', url: 'https://www.medals.pl/bc/r/uk1mqg.gif' },
  { country: 'United Kingdom', branch: 'UK Gallantry', name: 'Royal Red Cross (RRC)', url: 'https://www.medals.pl/bc/r/uk1crrc.gif' },
  { country: 'United Kingdom', branch: 'UK Orders', name: 'Order of the British Empire - Military (OBE)', url: 'https://www.medals.pl/bc/r/uk1obemb.gif' },
  { country: 'United Kingdom', branch: 'UK Orders', name: 'Order of the British Empire - Civil (OBE)', url: 'https://www.medals.pl/bc/r/uk1obecb.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'British Empire Medal - Military (BEM)', url: 'https://www.medals.pl/bc/r/uk1mbemb.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'British Empire Medal - Civil (BEM)', url: 'https://www.medals.pl/bc/r/uk1mbecg.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Meritorious Service Medal (MSM)', url: 'https://www.medals.pl/bc/r/uk1mmsa.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Korea Medal 1950-53', url: 'https://www.medals.pl/bc/r/uk1mko_m.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Campaign Service Medal 1962-2007', url: 'https://www.medals.pl/bc/r/uk1mcs_m.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Vietnam Service Medal 1968-73', url: 'https://www.medals.pl/bc/r/uk1mvns_m.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Vietnam Logistic and Support Medal', url: 'https://www.medals.pl/bc/r/uk1mvnlss.gif' },
  { country: 'United Kingdom', branch: 'UK Campaign Medals', name: 'Polar Medal', url: 'https://www.medals.pl/bc/r/uk1mpo.gif' },
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Star of Courage (SC)', url: 'https://www.medals.pl/bc/r/au2sco1.gif' },
  { country: 'Australia', branch: 'Australia Gallantry', name: 'Bravery Medal (BM)', url: 'https://www.medals.pl/bc/r/au2mbr1.gif' },
  { country: 'Australia', branch: 'Australia Commendations', name: 'Commendation for Brave Conduct', url: 'https://www.medals.pl/bc/r/au2cobc.gif' },
  { country: 'Australia', branch: 'Australia Commendations', name: 'Nursing Service Cross (NSC)', url: 'https://www.medals.pl/bc/r/au2cns.gif' },
  { country: 'Australia', branch: 'Australia Orders', name: 'Medal of the Order of Australia - Military Division (OAM)', url: 'https://www.medals.pl/bc/r/au2moam.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Public Service Medal (PSM)', url: 'https://www.medals.pl/bc/r/au2mpus.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Antarctic Medal (AAM)', url: 'https://www.medals.pl/bc/r/au2maa.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Defence Force Service Medal (DFSM)', url: 'https://www.medals.pl/bc/r/au2mdfs.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Police Overseas Service Medal (POSM)', url: 'https://www.medals.pl/bc/r/au2mpoov.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Humanitarian Overseas Service Medal (HSM)', url: 'https://www.medals.pl/bc/r/au2mhuov.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'National Emergency Medal (NEM)', url: 'https://www.medals.pl/bc/r/au2mnem.gif' },
  { country: 'Australia', branch: 'Australia Service Medals', name: 'Australian Service Medal (ASM)', url: 'https://www.medals.pl/bc/r/au2mas.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'Australian Active Service Medal 1945-75', url: 'https://www.medals.pl/bc/r/au2maas4575.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'Australian Service Medal 1945-75', url: 'https://www.medals.pl/bc/r/au2mas4575.gif' },
  { country: 'Australia', branch: 'Australia Campaign Medals', name: 'Australian General Service Medal - Korea', url: 'https://www.medals.pl/bc/r/au2magsk.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Civilian Service Medal 1939-45', url: 'https://www.medals.pl/bc/r/au2mcvs.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: '80th Anniversary Armistice Medal 1988', url: 'https://www.medals.pl/bc/r/au2mjard.gif' },
  { country: 'Australia', branch: 'Australia Jubilee & Commemorative', name: 'Anniversary of National Service Medal 1951-72', url: 'https://www.medals.pl/bc/r/au2mjnsm5172.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Cross of Valour (CV)', url: 'https://www.medals.pl/bc/r/ca2cva.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Star of Courage (SC)', url: 'https://www.medals.pl/bc/r/ca2sco.gif' },
  { country: 'Canada', branch: 'Canada Gallantry', name: 'Medal of Bravery (MB)', url: 'https://www.medals.pl/bc/r/ca2mbr.gif' },
  { country: 'Canada', branch: 'Canada Orders', name: 'Order of Military Merit (OMM)', url: 'https://www.medals.pl/bc/r/ca2omm1.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Sacrifice Medal', url: 'https://www.medals.pl/bc/r/ca2msa.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Canadian Forces Decoration (CD)', url: 'https://www.medals.pl/bc/r/ca2dcf.gif' },
  { country: 'Canada', branch: 'Canada Service Medals', name: 'Royal Canadian Mounted Police Long Service Medal', url: 'https://www.medals.pl/bc/r/ca2mlsmp35.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Canadian Volunteer Service Medal - Korea', url: 'https://www.medals.pl/bc/r/ca2mkv.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Campaign Star - Expedition', url: 'https://www.medals.pl/bc/r/ca2sgcexp.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Service Medal - Afghanistan', url: 'https://www.medals.pl/bc/r/ca2mgsaf.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Service Medal - South West Asia', url: 'https://www.medals.pl/bc/r/ca2mgsswa.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'General Service Medal - Expedition', url: 'https://www.medals.pl/bc/r/ca2mgsexp.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - South Sudan', url: 'https://www.medals.pl/bc/r/ca2moss.gif' },
  { country: 'Canada', branch: 'Canada Campaign Medals', name: 'Operational Service Medal - Expedition', url: 'https://www.medals.pl/bc/r/ca2mosexp.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'New Zealand Service Medal 1946-49', url: 'https://www.medals.pl/bc/r/nz2ms46.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'General Service Medal - Korea', url: 'https://www.medals.pl/bc/r/nz2mgskr.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'Special Service Medal - Nuclear Testing', url: 'https://www.medals.pl/bc/r/nz2mss.gif' },
  { country: 'New Zealand', branch: 'New Zealand Campaign Medals', name: 'Special Service Medal - Erebus 1979', url: 'https://www.medals.pl/bc/r/nz2msser.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'New Zealand Antarctic Medal (NZAM)', url: 'https://www.medals.pl/bc/r/nz2manz.gif' },
  { country: 'New Zealand', branch: 'New Zealand Service Medals', name: 'NZ Police LS & GC Medal', url: 'https://www.medals.pl/bc/r/nz2mlsp.gif' },
  { country: 'New Zealand', branch: 'New Zealand Jubilee & Commemorative', name: 'NZ Commemorative Medal 1990', url: 'https://www.medals.pl/bc/r/nz2mco90.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Army Long Service & Good Conduct Medal', url: 'https://www.medals.pl/bc/r/uk1mlsa.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'Naval Long Service & Good Conduct Medal', url: 'https://www.medals.pl/bc/r/uk1mlsn.gif' },
  { country: 'United Kingdom', branch: 'UK Service Medals', name: 'RAF Long Service & Good Conduct Medal', url: 'https://www.medals.pl/bc/r/uk1mlsaf.gif' },
  // ─── BELGIUM ────────────────────────────────────────────────────────────────
  { country: 'Belgium', branch: 'Belgium Orders', name: "Order of Léopold", url: 'https://www.medals.pl/be/r/be1ole4.gif' },
  { country: 'Belgium', branch: 'Belgium Orders', name: "Order of Léopold II", url: 'https://www.medals.pl/be/r/be1oleii.gif' },
  { country: 'Belgium', branch: 'Belgium Gallantry & Crosses', name: 'Croix de Guerre 1914-18', url: 'https://www.medals.pl/be/r/be1cg18.gif' },
  { country: 'Belgium', branch: 'Belgium Gallantry & Crosses', name: 'Croix de Guerre 1940-45', url: 'https://www.medals.pl/be/r/be1cg40.gif' },
  { country: 'Belgium', branch: 'Belgium Campaign Medals', name: 'Commemorative Medal for the War 1914-1918', url: 'https://www.medals.pl/be/r/be1mc1418.gif' },
  { country: 'Belgium', branch: 'Belgium Campaign Medals', name: 'Liberation Commemorative Medal', url: 'https://www.medals.pl/be/r/be1mli.gif' },

  // ─── FRANCE ─────────────────────────────────────────────────────────────────
  { country: 'France', branch: 'France Orders', name: "Légion d'Honneur", url: 'https://www.medals.pl/fr/r/fr2olh4.gif' },
  { country: 'France', branch: 'France Gallantry & Crosses', name: "Médaille Militaire", url: 'https://www.medals.pl/fr/r/fr2mm.gif' },
  { country: 'France', branch: 'France Gallantry & Crosses', name: 'Croix de Guerre 1914-18', url: 'https://www.medals.pl/fr/r/fr2cdg14.gif' },
  { country: 'France', branch: 'France Gallantry & Crosses', name: 'Croix de Guerre 1939-45', url: 'https://www.medals.pl/fr/r/fr2cdg39.gif' },
  { country: 'France', branch: 'France Gallantry & Crosses', name: "Médaille de la Résistance", url: 'https://www.medals.pl/fr/r/fr2mre.gif' },
  { country: 'France', branch: 'France Gallantry & Crosses', name: 'Croix du Combattant', url: 'https://www.medals.pl/fr/r/fr2cc.gif' },
  { country: 'France', branch: 'France Campaign Medals', name: "Médaille de la France Libérée", url: 'https://www.medals.pl/fr/r/fr2mli.gif' },
  { country: 'France', branch: 'France Gallantry & Crosses', name: 'Croix du Combattant Volontaire 1914-18', url: 'https://www.medals.pl/fr/r/fr2ccv14.gif' },
  { country: 'France', branch: 'France Gallantry & Crosses', name: 'Croix du Combattant Volontaire de la Résistance', url: 'https://www.medals.pl/fr/r/fr2ccvr.gif' },
  { country: 'France', branch: 'France Campaign Medals', name: "Médaille commémorative de la Guerre 1939-1945", url: 'https://www.medals.pl/fr/r/fr2mcg39.gif' },

  // ─── ITALY ──────────────────────────────────────────────────────────────────
  { country: 'Italy', branch: 'Italy Orders', name: 'Military Order of Savoy', url: 'https://www.medals.pl/it/r/it1omi.gif' },
  { country: 'Italy', branch: 'Italy Orders', name: "Order of St. Maurice & St. Lazarus", url: 'https://www.medals.pl/it/r/it1oml.gif' },
  { country: 'Italy', branch: 'Italy Orders', name: 'Order of the Crown of Italy', url: 'https://www.medals.pl/it/r/it1ocr.gif' },
  { country: 'Italy', branch: 'Italy Orders', name: 'Order of Merit of the Italian Republic', url: 'https://www.medals.pl/it/r/it2ome.gif' },
  { country: 'Italy', branch: 'Italy Gallantry & Crosses', name: 'Medal for Military Valor', url: 'https://www.medals.pl/it/r/it2mvmi2.gif' },
  { country: 'Italy', branch: 'Italy Gallantry & Crosses', name: 'War Merit Cross', url: 'https://www.medals.pl/it/r/it2cmg.gif' },

  // ─── GREECE ─────────────────────────────────────────────────────────────────
  { country: 'Greece', branch: 'Greece Orders', name: 'Order of the Redeemer', url: 'https://www.medals.pl/gr/r/gr1ore.gif' },
  { country: 'Greece', branch: 'Greece Orders', name: 'Order of the Phoenix', url: 'https://www.medals.pl/gr/r/gr1oph.gif' },
  { country: 'Greece', branch: 'Greece Orders', name: 'Royal Order of George I', url: 'https://www.medals.pl/gr/r/gr1oge.gif' },
  { country: 'Greece', branch: 'Greece Gallantry & Crosses', name: 'Cross of Valour', url: 'https://www.medals.pl/gr/r/gr1cva.gif' },
  { country: 'Greece', branch: 'Greece Gallantry & Crosses', name: 'War Cross 1940', url: 'https://www.medals.pl/gr/r/gr1wc.gif' },
  { country: 'Greece', branch: 'Greece Gallantry & Crosses', name: 'Medal for Outstanding Acts', url: 'https://www.medals.pl/gr/r/gr1moab.gif' },
  { country: 'Greece', branch: 'Greece Campaign Medals', name: 'Commemorative Medal of War 1940-1941', url: 'https://www.medals.pl/gr/r/gr1mw4041b.gif' },
  { country: 'Greece', branch: 'Greece Campaign Medals', name: 'Commemorative Medal of War 1941-1945', url: 'https://www.medals.pl/gr/r/gr1mw4145b.gif' },

  // ─── NORWAY ─────────────────────────────────────────────────────────────────
  { country: 'Norway', branch: 'Norway Orders', name: 'Order of St. Olaf', url: 'https://www.medals.pl/no/r/no1ool.gif' },
  { country: 'Norway', branch: 'Norway Gallantry & Crosses', name: 'War Cross', url: 'https://www.medals.pl/no/r/no1cw.gif' },
  { country: 'Norway', branch: 'Norway Gallantry & Crosses', name: "Haakon VII's Cross of Liberty", url: 'https://www.medals.pl/no/r/no1cfr.gif' },
  { country: 'Norway', branch: 'Norway Gallantry & Crosses', name: "Haakon VII's Freedom Medal", url: 'https://www.medals.pl/no/r/no1mfr.gif' },
  { country: 'Norway', branch: 'Norway Campaign Medals', name: 'War Medal', url: 'https://www.medals.pl/no/r/no1wam.gif' },
  { country: 'Norway', branch: 'Norway Campaign Medals', name: 'Defense Participation Medal 1940-45', url: 'https://www.medals.pl/no/r/no1m4045.gif' },
  { country: 'Norway', branch: 'Norway Orders', name: "St. Olaf's Medal with Oak Wreath", url: 'https://www.medals.pl/no/r/no1molo.gif' },

  // ─── NETHERLANDS ────────────────────────────────────────────────────────────
  { country: 'Netherlands', branch: 'Netherlands Orders', name: 'Military Order of William', url: 'https://www.medals.pl/nl/r/nl1owi.gif' },
  { country: 'Netherlands', branch: 'Netherlands Orders', name: 'Order of Orange-Nassau', url: 'https://www.medals.pl/nl/r/nl1oon.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Bronze Lion', url: 'https://www.medals.pl/nl/r/nl1bli.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Bronze Cross', url: 'https://www.medals.pl/nl/r/nl1cbr.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Flying Cross', url: 'https://www.medals.pl/nl/r/nl1cfl.gif' },
  { country: 'Netherlands', branch: 'Netherlands Gallantry & Crosses', name: 'Cross of Merit', url: 'https://www.medals.pl/nl/r/nl1cme.gif' },

  // ─── RUSSIA ─────────────────────────────────────────────────────────────────
  { country: 'Russia', branch: 'Russia Orders', name: 'Cross/Medal of St. George', url: 'https://www.medals.pl/ru/r/ru1ogeo.gif' },
  { country: 'Russia', branch: 'Russia Orders', name: 'Order of St. Vladimir', url: 'https://www.medals.pl/ru/r/ru1ovla.gif' },
  { country: 'Russia', branch: 'Russia Orders', name: 'Order of St. Anne', url: 'https://www.medals.pl/ru/r/ru1oann.gif' },
  { country: 'Russia', branch: 'Russia Orders', name: 'Order of St. Stanislas', url: 'https://www.medals.pl/ru/r/ru1osta.gif' },

  // ─── POLAND ─────────────────────────────────────────────────────────────────
  { country: 'Poland', branch: 'Poland Orders', name: 'Order Virtuti Militari', url: 'https://www.medals.pl/pl/r/pl4ovm.gif' },
  { country: 'Poland', branch: 'Poland Orders', name: 'Order of Polonia Restituta', url: 'https://www.medals.pl/pl/r/pl4opr.gif' },
  { country: 'Poland', branch: 'Poland Gallantry & Crosses', name: 'Cross of Valor', url: 'https://www.medals.pl/pl/r/pl2cvab.gif' },
  { country: 'Poland', branch: 'Poland Gallantry & Crosses', name: 'Cross of Merit', url: 'https://www.medals.pl/pl/r/pl2cme.gif' },

  // ─── LUXEMBOURG ─────────────────────────────────────────────────────────────
  { country: 'Luxembourg', branch: 'Luxembourg Orders', name: 'Order of Adolph of Nassau', url: 'https://www.medals.pl/lu/r/lu1oan.gif' },
  { country: 'Luxembourg', branch: 'Luxembourg Gallantry & Crosses', name: 'Croix de Guerre', url: 'https://www.medals.pl/lu/r/lu1cg.gif' },

];