// ─── RIBBON LIBRARY ─────────────────────────────────────────────────────────
// Sources:
//   - EZRackBuilder / USAMM — 1118 real US awards, all branches + auxiliaries
//   - medals.org.uk — 1274 international awards across 31 countries + UN
// Total: 164 ribbons. Auto-generated. DO NOT hand-edit.

export interface RibbonTemplate {
  country: string;
  branch: string;
  name: string;
  url: string;
  sku?: string;
}

export const RIBBON_COUNTRIES: string[] = ['United States'];

export const RIBBON_BRANCHES_BY_COUNTRY: Record<string, string[]> = {
  'United States': ['US Army', 'US Navy', 'US Marine Corps', 'US Air Force'],
};

export const RIBBON_TEMPLATES: RibbonTemplate[] = [
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Aerial Achievement', url: 'https://i.ezr.io/products3/400_AFAAMR.jpg?h=36&w=132&auto=format', sku: '400 AFAAMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Combat Action', url: 'https://i.ezr.io/products3/639.jpg?h=36&w=132&auto=format', sku: '639' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Cross', url: 'https://i.ezr.io/products3/405_AFCMR.jpg?h=36&w=132&auto=format', sku: '405 AFCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Distinguished Service', url: 'https://i.ezr.io/products3/406_AFAFDSMR.jpg?h=36&w=132&auto=format', sku: '406 AFAFDSMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Good Conduct', url: 'https://i.ezr.io/products3/409_AFGCMR.jpg?h=36&w=132&auto=format', sku: '409 AFGCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Meritorious Unit Award', url: 'https://i.ezr.io/products3/411_AFMUAR.jpg?h=36&w=132&auto=format', sku: '411 AFMUAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force NCO Professional Military Education Graduate', url: 'https://i.ezr.io/products3/528_AFNCOPMEGR.jpg?h=36&w=132&auto=format', sku: '528 AFNCOPMEGR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Nuclear Deterrence Operations ', url: 'https://i.ezr.io/products3/84370.jpg?h=36&w=132&auto=format', sku: '84370' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Presidential Unit Citation', url: 'https://i.ezr.io/products3/416_AFPUCR.jpg?h=36&w=132&auto=format', sku: '416 AFPUCR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Recruiting', url: 'https://i.ezr.io/products3/418_AFRECR.jpg?h=36&w=132&auto=format', sku: '418 AFRECR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Remote Combat Effects Campaign', url: 'https://i.ezr.io/products3/85495.jpg?h=36&w=132&auto=format', sku: '85495' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Special Duty', url: 'https://i.ezr.io/products3/81166.jpg?h=36&w=132&auto=format', sku: '81166' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Force Training', url: 'https://i.ezr.io/products3/419_AFTR.jpg?h=36&w=132&auto=format', sku: '419 AFTR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air Reserve Meritorious Service', url: 'https://i.ezr.io/products3/421_AFARMSMR.jpg?h=36&w=132&auto=format', sku: '421 AFARMSMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Achievement', url: 'https://i.ezr.io/products3/403_AFAFAMR.jpg?h=36&w=132&auto=format', sku: '403 AFAFAMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Campaign', url: 'https://i.ezr.io/products3/402_AFASCMR.jpg?h=36&w=132&auto=format', sku: '402 AFASCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Commendation', url: 'https://i.ezr.io/products3/404_AFAFCMR.jpg?h=36&w=132&auto=format', sku: '404 AFAFCMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Expeditionary Service', url: 'https://i.ezr.io/products3/407_AFAFESR.jpg?h=36&w=132&auto=format', sku: '407 AFAFESR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Expeditionary With Gold Frame', url: 'https://i.ezr.io/products3/408_AFERGFR.jpg?h=36&w=132&auto=format', sku: '408 AFERGFR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Longevity Service Award', url: 'https://i.ezr.io/products3/410_AFLSAR.jpg?h=36&w=132&auto=format', sku: '410 AFLSAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Organizational Excellence Award', url: 'https://i.ezr.io/products3/412_AFOEAR.jpg?h=36&w=132&auto=format', sku: '412 AFOEAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Outstanding Unit Award', url: 'https://i.ezr.io/products3/413_AFOUAR.jpg?h=36&w=132&auto=format', sku: '413 AFOUAR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Overseas  Long Tour', url: 'https://i.ezr.io/products3/414_AFORLTR.jpg?h=36&w=132&auto=format', sku: '414 AFORLTR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Overseas  Short Tour', url: 'https://i.ezr.io/products3/415_AFORSTR.jpg?h=36&w=132&auto=format', sku: '415 AFORSTR' },
  { country: 'United States', branch: 'US Air Force', name: 'Air and Space Recognition', url: 'https://i.ezr.io/products3/417_AFRR.jpg?h=36&w=132&auto=format', sku: '417 AFRR' },
  { country: 'United States', branch: 'US Air Force', name: 'Airmans', url: 'https://i.ezr.io/products3/422_AFAMR.jpg?h=36&w=132&auto=format', sku: '422 AFAMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Armed Forces Reserve Air Force', url: 'https://i.ezr.io/products3/427_AF.jpg?h=36&w=132&auto=format', sku: '427 AF' },
  { country: 'United States', branch: 'US Air Force', name: 'Basic Military Training Honor Graduate (Air Force)', url: 'https://i.ezr.io/products3/441_AFBMTHGR.jpg?h=36&w=132&auto=format', sku: '441 AFBMTHGR' },
  { country: 'United States', branch: 'US Air Force', name: 'Combat Readiness', url: 'https://i.ezr.io/products3/462_AFCRMR.jpg?h=36&w=132&auto=format', sku: '462 AFCRMR' },
  { country: 'United States', branch: 'US Air Force', name: 'Gallant Unit Citation', url: 'https://i.ezr.io/products3/477_AFGUCR.jpg?h=36&w=132&auto=format', sku: '477 AFGUCR' },
  { country: 'United States', branch: 'US Air Force', name: 'LA F.E. Herbert Meritorious Unit Commendation (with USAF frame)', url: 'https://i.ezr.io/products3/7658LAUSAFGF.jpg?h=36&w=132&auto=format', sku: '7658LAUSAFGF' },
  { country: 'United States', branch: 'US Air Force', name: 'Military Training Instructor', url: 'https://i.ezr.io/products3/499_AFMTIR.jpg?h=36&w=132&auto=format', sku: '499 AFMTIR' },
  { country: 'United States', branch: 'US Air Force', name: 'Outstanding Airman of the Year', url: 'https://i.ezr.io/products3/530_AFOAOTYR.jpg?h=36&w=132&auto=format', sku: '530 AFOAOTYR' },
  { country: 'United States', branch: 'US Air Force', name: 'Small Arms Expert Marksmanship', url: 'https://i.ezr.io/products3/574_AFSAEMR.jpg?h=36&w=132&auto=format', sku: '574 AFSAEMR' },
  { country: 'United States', branch: 'US Air Force', name: 'United States Air Force Commemorative', url: 'https://i.ezr.io/products3/84348.jpg?h=36&w=132&auto=format', sku: '84348' },
  { country: 'United States', branch: 'US Army', name: 'Afghanistan Campaign', url: 'https://i.ezr.io/products3/401_ARACMR.jpg?h=36&w=132&auto=format', sku: '401 ARACMR' },
  { country: 'United States', branch: 'US Army', name: 'Air', url: 'https://i.ezr.io/products3/420_ARAMR.jpg?h=36&w=132&auto=format', sku: '420 ARAMR' },
  { country: 'United States', branch: 'US Army', name: 'American Campaign', url: 'https://i.ezr.io/products3/423_ARCAMR.jpg?h=36&w=132&auto=format', sku: '423 ARCAMR' },
  { country: 'United States', branch: 'US Army', name: 'American Defense', url: 'https://i.ezr.io/products3/424_ARDMR.jpg?h=36&w=132&auto=format', sku: '424 ARDMR' },
  { country: 'United States', branch: 'US Army', name: 'Antarctica Service', url: 'https://i.ezr.io/products3/425_ARASMR.jpg?h=36&w=132&auto=format', sku: '425 ARASMR' },
  { country: 'United States', branch: 'US Army', name: 'Armed Forces Expeditionary', url: 'https://i.ezr.io/products3/426_AREMR.jpg?h=36&w=132&auto=format', sku: '426 AREMR' },
  { country: 'United States', branch: 'US Army', name: 'Armed Forces Reserve Army', url: 'https://i.ezr.io/products3/427_ARRMR.jpg?h=36&w=132&auto=format', sku: '427 ARRMR' },
  { country: 'United States', branch: 'US Army', name: 'Armed Forces Service', url: 'https://i.ezr.io/products3/428_ARSMR.jpg?h=36&w=132&auto=format', sku: '428 ARSMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Achievement', url: 'https://i.ezr.io/products3/429_ARACHMR.jpg?h=36&w=132&auto=format', sku: '429 ARACHMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Commanders Award for Public Service', url: 'https://i.ezr.io/products3/609_ARM-COMM-PUB.jpg?h=36&w=132&auto=format', sku: '609 ARM-COMM-PUB' },
  { country: 'United States', branch: 'US Army', name: 'Army Commendation', url: 'https://i.ezr.io/products3/430_ARCMR.jpg?h=36&w=132&auto=format', sku: '430 ARCMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Distinguished Service', url: 'https://i.ezr.io/products3/592_ARMYDIST.jpg?h=36&w=132&auto=format', sku: '592 ARMYDIST' },
  { country: 'United States', branch: 'US Army', name: 'Army Distinguished Service Cross', url: 'https://i.ezr.io/products3/472_ARDSCR.jpg?h=36&w=132&auto=format', sku: '472 ARDSCR' },
  { country: 'United States', branch: 'US Army', name: 'Army Exceptional Public Service', url: 'https://i.ezr.io/products3/612_ARM-EXCP-PUB.jpg?h=36&w=132&auto=format', sku: '612 ARM-EXCP-PUB' },
  { country: 'United States', branch: 'US Army', name: 'Army Good Conduct', url: 'https://i.ezr.io/products3/431_ARGCMR.jpg?h=36&w=132&auto=format', sku: '431 ARGCMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Meritorious Honor Award', url: 'https://i.ezr.io/products3/613.jpg?h=36&w=132&auto=format', sku: '613' },
  { country: 'United States', branch: 'US Army', name: 'Army Meritorious Unit Citation', url: 'https://i.ezr.io/products3/432_ARMUCR.jpg?h=36&w=132&auto=format', sku: '432 ARMUCR' },
  { country: 'United States', branch: 'US Army', name: 'Army NCO Professional Development', url: 'https://i.ezr.io/products3/529_ARNONCOPDR.jpg?h=36&w=132&auto=format', sku: '529 ARNONCOPDR' },
  { country: 'United States', branch: 'US Army', name: 'Army Overseas Service', url: 'https://i.ezr.io/products3/433_AROSR.jpg?h=36&w=132&auto=format', sku: '433 AROSR' },
  { country: 'United States', branch: 'US Army', name: 'Army Presidential Unit Citation', url: 'https://i.ezr.io/products3/434_ARPUCR.jpg?h=36&w=132&auto=format', sku: '434 ARPUCR' },
  { country: 'United States', branch: 'US Army', name: 'Army Recruiting', url: 'https://i.ezr.io/products3/85786.jpg?h=36&w=132&auto=format', sku: '85786' },
  { country: 'United States', branch: 'US Army', name: 'Army Reserve Components Achievement', url: 'https://i.ezr.io/products3/435_ARRRCAMR.jpg?h=36&w=132&auto=format', sku: '435 ARRRCAMR' },
  { country: 'United States', branch: 'US Army', name: 'Army Reserve Components Overseas Training', url: 'https://i.ezr.io/products3/568_ARRCOTR.jpg?h=36&w=132&auto=format', sku: '568 ARRCOTR' },
  { country: 'United States', branch: 'US Army', name: 'Army Sea Duty', url: 'https://i.ezr.io/products3/643.jpg?h=36&w=132&auto=format', sku: '643' },
  { country: 'United States', branch: 'US Army', name: 'Army Service', url: 'https://i.ezr.io/products3/436_ARSR.jpg?h=36&w=132&auto=format', sku: '436 ARSR' },
  { country: 'United States', branch: 'US Army', name: 'Army Soldiers  - Heroism', url: 'https://i.ezr.io/products3/437_ARSMHR.jpg?h=36&w=132&auto=format', sku: '437 ARSMHR' },
  { country: 'United States', branch: 'US Army', name: 'Army Superior Unit Award', url: 'https://i.ezr.io/products3/438_ARSUAR.jpg?h=36&w=132&auto=format', sku: '438 ARSUAR' },
  { country: 'United States', branch: 'US Army', name: 'Army Valorous Unit Citation Award', url: 'https://i.ezr.io/products3/439_ARVUCAR.jpg?h=36&w=132&auto=format', sku: '439 ARVUCAR' },
  { country: 'United States', branch: 'US Army', name: 'Belgian Croix de Guerre', url: 'https://i.ezr.io/products3/589_BELGCROIX.jpg?h=36&w=132&auto=format', sku: '589 BELGCROIX' },
  { country: 'United States', branch: 'US Army', name: 'Bronze Star', url: 'https://i.ezr.io/products3/443_ARBSR.jpg?h=36&w=132&auto=format', sku: '443 ARBSR' },
  { country: 'United States', branch: 'US Army', name: 'Cold War', url: 'https://i.ezr.io/products3/662.jpg?h=36&w=132&auto=format', sku: '662' },
  { country: 'United States', branch: 'US Army', name: 'Commandants Letter of Commendation', url: 'https://i.ezr.io/products3/463_CGCLOCR.jpg?h=36&w=132&auto=format', sku: '463 CGCLOCR' },
  { country: 'United States', branch: 'US Army', name: 'Defense Meritorious Service', url: 'https://i.ezr.io/products3/468_ARDMSMR.jpg?h=36&w=132&auto=format', sku: '468 ARDMSMR' },
  { country: 'United States', branch: 'US Army', name: 'Defense Superior Service', url: 'https://i.ezr.io/products3/469_ARDSSMR.jpg?h=36&w=132&auto=format', sku: '469 ARDSSMR' },
  { country: 'United States', branch: 'US Army', name: 'European - African - Middle Eastern Campaign', url: 'https://i.ezr.io/products3/474_AREAMECMR.jpg?h=36&w=132&auto=format', sku: '474 AREAMECMR' },
  { country: 'United States', branch: 'US Army', name: 'Global War on Terrorism Expeditionary', url: 'https://i.ezr.io/products3/478_ARGWTEMR.jpg?h=36&w=132&auto=format', sku: '478 ARGWTEMR' },
  { country: 'United States', branch: 'US Army', name: 'Global War on Terrorism Service', url: 'https://i.ezr.io/products3/479_ARGWTSMR.jpg?h=36&w=132&auto=format', sku: '479 ARGWTSMR' },
  { country: 'United States', branch: 'US Army', name: 'Gold Lifesaving', url: 'https://i.ezr.io/products3/586_GOLDLIFE.jpg?h=36&w=132&auto=format', sku: '586 GOLDLIFE' },
  { country: 'United States', branch: 'US Army', name: 'Holland 4 Days Cross Marches Nijmegen', url: 'https://i.ezr.io/products3/85175.jpg?h=36&w=132&auto=format', sku: '85175' },
  { country: 'United States', branch: 'US Army', name: 'Humanitarian Service', url: 'https://i.ezr.io/products3/480_ARHSMR.jpg?h=36&w=132&auto=format', sku: '480 ARHSMR' },
  { country: 'United States', branch: 'US Army', name: 'Inherent Resolve Campaign', url: 'https://i.ezr.io/products3/81270.jpg?h=36&w=132&auto=format', sku: '81270' },
  { country: 'United States', branch: 'US Army', name: 'Inter-American Defense Board', url: 'https://i.ezr.io/products3/481_ARIADBMR.jpg?h=36&w=132&auto=format', sku: '481 ARIADBMR' },
  { country: 'United States', branch: 'US Army', name: 'International March of Diekirch', url: 'https://i.ezr.io/products3/85785.jpg?h=36&w=132&auto=format', sku: '85785' },
  { country: 'United States', branch: 'US Army', name: 'Iraq Campaign', url: 'https://i.ezr.io/products3/482_ARICMR.jpg?h=36&w=132&auto=format', sku: '482 ARICMR' },
  { country: 'United States', branch: 'US Army', name: 'Joint Meritorious Unit Award with Army Frame', url: 'https://i.ezr.io/products3/484_ARJMUAR.jpg?h=36&w=132&auto=format', sku: '484 ARJMUAR' },
  { country: 'United States', branch: 'US Army', name: 'Joint Service Achievement', url: 'https://i.ezr.io/products3/485_ARJSAMR.jpg?h=36&w=132&auto=format', sku: '485 ARJSAMR' },
  { country: 'United States', branch: 'US Army', name: 'Joint Service Commendation', url: 'https://i.ezr.io/products3/486_ARJSCMR.jpg?h=36&w=132&auto=format', sku: '486 ARJSCMR' },
  { country: 'United States', branch: 'US Army', name: 'Korea Defense Service', url: 'https://i.ezr.io/products3/486-A_ARKDSMR.jpg?h=36&w=132&auto=format', sku: '486-A ARKDSMR' },
  { country: 'United States', branch: 'US Army', name: 'Kosovo Campaign', url: 'https://i.ezr.io/products3/488_ARKCMR.jpg?h=36&w=132&auto=format', sku: '488 ARKCMR' },
  { country: 'United States', branch: 'US Army', name: 'Kuwait Liberation of Kuwait', url: 'https://i.ezr.io/products3/489_ARKLMKR.jpg?h=36&w=132&auto=format', sku: '489 ARKLMKR' },
  { country: 'United States', branch: 'US Army', name: 'Legion of Merit', url: 'https://i.ezr.io/products3/490_ARLOFR.jpg?h=36&w=132&auto=format', sku: '490 ARLOFR' },
  { country: 'United States', branch: 'US Army', name: 'Legion of Merit Officer', url: 'https://i.ezr.io/products3/640.jpg?h=36&w=132&auto=format', sku: '640' },
  { country: 'United States', branch: 'US Army', name: 'Meritorious Service', url: 'https://i.ezr.io/products3/498_ARMSMR.jpg?h=36&w=132&auto=format', sku: '498 ARMSMR' },
  { country: 'United States', branch: 'US Army', name: 'Mexican Service - Army', url: 'https://i.ezr.io/products3/594_MEX-SVC-RBARMY.jpg?h=36&w=132&auto=format', sku: '594 MEX-SVC-RBARMY' },
  { country: 'United States', branch: 'US Army', name: 'Multi-National Forces and Observers', url: 'https://i.ezr.io/products3/500_ARMNFOMR.jpg?h=36&w=132&auto=format', sku: '500 ARMNFOMR' },
  { country: 'United States', branch: 'US Army', name: 'NATO', url: 'https://i.ezr.io/products3/504.jpg?h=36&w=132&auto=format', sku: '504' },
  { country: 'United States', branch: 'US Army', name: 'NATO Article 5 Active Endeavour', url: 'https://i.ezr.io/products3/654.jpg?h=36&w=132&auto=format', sku: '654' },
  { country: 'United States', branch: 'US Army', name: 'NATO ISAF (International Security Assistance Force)', url: 'https://i.ezr.io/products3/637_NATO-ISAF-R.jpg?h=36&w=132&auto=format', sku: '637 NATO-ISAF-R' },
  { country: 'United States', branch: 'US Army', name: 'NATO Kosovo', url: 'https://i.ezr.io/products3/503_ARNATOKMR.jpg?h=36&w=132&auto=format', sku: '503 ARNATOKMR' },
  { country: 'United States', branch: 'US Army', name: 'NATO Meritorious Service', url: 'https://i.ezr.io/products3/653.jpg?h=36&w=132&auto=format', sku: '653' },
  { country: 'United States', branch: 'US Army', name: 'NATO NTM-IRAQ (NATO Training Mission Iraq)', url: 'https://i.ezr.io/products3/637.jpg?h=36&w=132&auto=format', sku: '637' },
  { country: 'United States', branch: 'US Army', name: 'NATO Non-Article 5', url: 'https://i.ezr.io/products3/637_NATO-NA5.jpg?h=36&w=132&auto=format', sku: '637 NATO-NA5' },
  { country: 'United States', branch: 'US Army', name: 'NATO Non-Article 5 for the Balkans', url: 'https://i.ezr.io/products3/641.jpg?h=36&w=132&auto=format', sku: '641' },
  { country: 'United States', branch: 'US Army', name: 'NATO Operation Resolute Support', url: 'https://i.ezr.io/products3/637_NATO-ORS.jpg?h=36&w=132&auto=format', sku: '637 NATO-ORS' },
  { country: 'United States', branch: 'US Army', name: 'National Defense Service', url: 'https://i.ezr.io/products3/501_ARNDSMR.jpg?h=36&w=132&auto=format', sku: '501 ARNDSMR' },
  { country: 'United States', branch: 'US Army', name: 'Philippine Independence', url: 'https://i.ezr.io/products3/533_ARPIMR.jpg?h=36&w=132&auto=format', sku: '533 ARPIMR' },
  { country: 'United States', branch: 'US Army', name: 'Philippine Presidential Unit Citation with Army Frame', url: 'https://i.ezr.io/products3/536_ARPPUCR.jpg?h=36&w=132&auto=format', sku: '536 ARPPUCR' },
  { country: 'United States', branch: 'US Army', name: 'Presidential Inauguration Support', url: 'https://i.ezr.io/products3/85996.jpg?h=36&w=132&auto=format', sku: '85996' },
  { country: 'United States', branch: 'US Army', name: 'Prisoner of War', url: 'https://i.ezr.io/products3/538_ARPOWMR.jpg?h=36&w=132&auto=format', sku: '538 ARPOWMR' },
  { country: 'United States', branch: 'US Army', name: 'Purple Heart', url: 'https://i.ezr.io/products3/539_ARPHR.jpg?h=36&w=132&auto=format', sku: '539 ARPHR' },
  { country: 'United States', branch: 'US Army', name: 'Republic of Korea Presidential Unit Citation with Army Frame', url: 'https://i.ezr.io/products3/542_ARRKPCR.jpg?h=36&w=132&auto=format', sku: '542 ARRKPCR' },
  { country: 'United States', branch: 'US Army', name: 'Saudi Arabian  for the Liberation of Kuwait', url: 'https://i.ezr.io/products3/571_ARSAMLKR.jpg?h=36&w=132&auto=format', sku: '571 ARSAMLKR' },
  { country: 'United States', branch: 'US Army', name: 'Silver Lifesaving', url: 'https://i.ezr.io/products3/587_SILVLIFE.jpg?h=36&w=132&auto=format', sku: '587 SILVLIFE' },
  { country: 'United States', branch: 'US Army', name: 'Silver Star', url: 'https://i.ezr.io/products3/573_ARSSMR.jpg?h=36&w=132&auto=format', sku: '573 ARSSMR' },
  { country: 'United States', branch: 'US Army', name: 'Southwest Asia Service', url: 'https://i.ezr.io/products3/575_ARSWASMR.jpg?h=36&w=132&auto=format', sku: '575 ARSWASMR' },
  { country: 'United States', branch: 'US Army', name: 'United Nations', url: 'https://i.ezr.io/products3/579_ARUNMR.jpg?h=36&w=132&auto=format', sku: '579 ARUNMR' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Advance Mission in Cambodia ', url: 'https://i.ezr.io/products3/646.jpg?h=36&w=132&auto=format', sku: '646' },
  { country: 'United States', branch: 'US Army', name: 'United Nations In Service of Peace Commemorative', url: 'https://i.ezr.io/products3/84342.jpg?h=36&w=132&auto=format', sku: '84342' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Mission in Haiti', url: 'https://i.ezr.io/products3/645.jpg?h=36&w=132&auto=format', sku: '645' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Operation in Somalia (UNOSOM)', url: 'https://i.ezr.io/products3/644.jpg?h=36&w=132&auto=format', sku: '644' },
  { country: 'United States', branch: 'US Army', name: 'United Nations Protection Force (UNPROFOR)', url: 'https://i.ezr.io/products3/81047.jpg?h=36&w=132&auto=format', sku: '81047' },
  { country: 'United States', branch: 'US Army', name: 'United States Army Commemorative', url: 'https://i.ezr.io/products3/84349.jpg?h=36&w=132&auto=format', sku: '84349' },
  { country: 'United States', branch: 'US Army', name: 'Womens Army Corps Service', url: 'https://i.ezr.io/products3/581_ARWACSMR.jpg?h=36&w=132&auto=format', sku: '581 ARWACSMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Armed Forces Reserve Marine Corps', url: 'https://i.ezr.io/products3/427_MC.jpg?h=36&w=132&auto=format', sku: '427 MC' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps China Service', url: 'https://i.ezr.io/products3/444_MCCSMR.jpg?h=36&w=132&auto=format', sku: '444 MCCSMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Combat Instructor', url: 'https://i.ezr.io/products3/83998.jpg?h=36&w=132&auto=format', sku: '83998' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Drill Instructor', url: 'https://i.ezr.io/products3/491_MCMCDIR.jpg?h=36&w=132&auto=format', sku: '491 MCMCDIR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Expeditionary', url: 'https://i.ezr.io/products3/492_MCEMR.jpg?h=36&w=132&auto=format', sku: '492 MCEMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Good Conduct', url: 'https://i.ezr.io/products3/493_MMCGR.jpg?h=36&w=132&auto=format', sku: '493 MMCGR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Recruiting', url: 'https://i.ezr.io/products3/495_MCRR.jpg?h=36&w=132&auto=format', sku: '495 MCRR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Reserve Service', url: 'https://i.ezr.io/products3/590_MRNRESERV.jpg?h=36&w=132&auto=format', sku: '590 MRNRESERV' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Marine Corps Security Guard', url: 'https://i.ezr.io/products3/496_MCSGR.jpg?h=36&w=132&auto=format', sku: '496 MCSGR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'Selected Marine Corps Reserve', url: 'https://i.ezr.io/products3/572_MCSMCRMR.jpg?h=36&w=132&auto=format', sku: '572 MCSMCRMR' },
  { country: 'United States', branch: 'US Marine Corps', name: 'United States Marine Corps Commemorative', url: 'https://i.ezr.io/products3/84350.jpg?h=36&w=132&auto=format', sku: '84350' },
  { country: 'United States', branch: 'US Navy', name: 'Armed Forces Reserve Navy', url: 'https://i.ezr.io/products3/427_NAVY.jpg?h=36&w=132&auto=format', sku: '427 NAVY' },
  { country: 'United States', branch: 'US Navy', name: 'Combat Action', url: 'https://i.ezr.io/products3/461_NCAR.jpg?h=36&w=132&auto=format', sku: '461 NCAR' },
  { country: 'United States', branch: 'US Navy', name: 'Fleet Marine Force', url: 'https://i.ezr.io/products3/475_NFMFR.jpg?h=36&w=132&auto=format', sku: '475 NFMFR' },
  { country: 'United States', branch: 'US Navy', name: 'Joint Meritorious Unit Award with NAVY/AF/MC/CG Frame', url: 'https://i.ezr.io/products3/483_NJMAR.jpg?h=36&w=132&auto=format', sku: '483 NJMAR' },
  { country: 'United States', branch: 'US Navy', name: 'Naval Reserve Meritorious Service', url: 'https://i.ezr.io/products3/505_NRMSMR.jpg?h=36&w=132&auto=format', sku: '505 NRMSMR' },
  { country: 'United States', branch: 'US Navy', name: 'Naval Reserve Sea Service', url: 'https://i.ezr.io/products3/506_NRSSR.jpg?h=36&w=132&auto=format', sku: '506 NRSSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps', url: 'https://i.ezr.io/products3/509_NNMCMR.jpg?h=36&w=132&auto=format', sku: '509 NNMCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps Achievement', url: 'https://i.ezr.io/products3/507_NMCAMR.jpg?h=36&w=132&auto=format', sku: '507 NMCAMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps Commendation', url: 'https://i.ezr.io/products3/508_NMCCMR.jpg?h=36&w=132&auto=format', sku: '508 NMCCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy & Marine Corps Overseas Service', url: 'https://i.ezr.io/products3/510_NNMOSR.jpg?h=36&w=132&auto=format', sku: '510 NNMOSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Arctic Service', url: 'https://i.ezr.io/products3/511_NASR.jpg?h=36&w=132&auto=format', sku: '511 NASR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Basic Military Training Honor Graduate', url: 'https://i.ezr.io/products3/692.jpg?h=36&w=132&auto=format', sku: '692' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Ceremonial Guard', url: 'https://i.ezr.io/products3/599_NAVCERMGD.jpg?h=36&w=132&auto=format', sku: '599 NAVCERMGD' },
  { country: 'United States', branch: 'US Navy', name: 'Navy China Service', url: 'https://i.ezr.io/products3/444_NCSMR.jpg?h=36&w=132&auto=format', sku: '444 NCSMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Cross', url: 'https://i.ezr.io/products3/512_NCMR.jpg?h=36&w=132&auto=format', sku: '512 NCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Distinguished Public Service', url: 'https://i.ezr.io/products3/620_NAV-DIST-PUB.jpg?h=36&w=132&auto=format', sku: '620 NAV-DIST-PUB' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Distinguished Service', url: 'https://i.ezr.io/products3/515_NDSMR.jpg?h=36&w=132&auto=format', sku: '515 NDSMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy E', url: 'https://i.ezr.io/products3/516_NER.jpg?h=36&w=132&auto=format', sku: '516 NER' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Expeditionary', url: 'https://i.ezr.io/products3/517_NEMR.jpg?h=36&w=132&auto=format', sku: '517 NEMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Expert Pistol', url: 'https://i.ezr.io/products3/518_NEPMR.jpg?h=36&w=132&auto=format', sku: '518 NEPMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Expert Rifleman', url: 'https://i.ezr.io/products3/519_NERR.jpg?h=36&w=132&auto=format', sku: '519 NERR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Good Conduct', url: 'https://i.ezr.io/products3/520_NGCMR.jpg?h=36&w=132&auto=format', sku: '520 NGCMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Meritorious Public Service', url: 'https://i.ezr.io/products3/622_NAV-MER-PUB.jpg?h=36&w=132&auto=format', sku: '622 NAV-MER-PUB' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Meritorious Unit Commendation', url: 'https://i.ezr.io/products3/521_NMUCR.jpg?h=36&w=132&auto=format', sku: '521 NMUCR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Presidential Unit Citation', url: 'https://i.ezr.io/products3/523_NPUCR.jpg?h=36&w=132&auto=format', sku: '523 NPUCR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Recruit Training Service', url: 'https://i.ezr.io/products3/540_NRTSR.jpg?h=36&w=132&auto=format', sku: '540 NRTSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Recruiting Service', url: 'https://i.ezr.io/products3/524_NRSR.jpg?h=36&w=132&auto=format', sku: '524 NRSR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Reserve', url: 'https://i.ezr.io/products3/525_NRMR.jpg?h=36&w=132&auto=format', sku: '525 NRMR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Reserve Specialist Commendation', url: 'https://i.ezr.io/products3/85501.jpg?h=36&w=132&auto=format', sku: '85501' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Sea Service Deployment', url: 'https://i.ezr.io/products3/526_NSSDR.jpg?h=36&w=132&auto=format', sku: '526 NSSDR' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Superior Public Service', url: 'https://i.ezr.io/products3/624_NAV-SUP-PUB.jpg?h=36&w=132&auto=format', sku: '624 NAV-SUP-PUB' },
  { country: 'United States', branch: 'US Navy', name: 'Navy Unit Commendation', url: 'https://i.ezr.io/products3/527_NUCR.jpg?h=36&w=132&auto=format', sku: '527 NUCR' },
  { country: 'United States', branch: 'US Navy', name: 'Philippine Presidential Unit Citation - AF/N/MC/CG Frame', url: 'https://i.ezr.io/products3/537.jpg?h=36&w=132&auto=format', sku: '537' },
  { country: 'United States', branch: 'US Navy', name: 'Republic of Korea Presidential Unit Citation with Navy Frame', url: 'https://i.ezr.io/products3/543_NRKPCR.jpg?h=36&w=132&auto=format', sku: '543 NRKPCR' },
  { country: 'United States', branch: 'US Navy', name: 'United States Navy Commemorative', url: 'https://i.ezr.io/products3/84351.jpg?h=36&w=132&auto=format', sku: '84351' },
  // ─── INTERNATIONAL ───
  // ─── NATO ───
  // ─── UNITED NATIONS ───


];
