// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tag-hero/HudScan.tsx": () => import("../components/mockups/tag-hero/HudScan.tsx"),
  "./components/mockups/tag-hero/SignalBroadcast.tsx": () => import("../components/mockups/tag-hero/SignalBroadcast.tsx"),
  "./components/mockups/tag-hero/SplitCommand.tsx": () => import("../components/mockups/tag-hero/SplitCommand.tsx")
};
